import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';const s=fs.readFileSync(new URL('../ea/XauCloud-Apex.mq5',import.meta.url),'utf8');
test('no broker SL',()=>{assert.doesNotMatch(s,/trade\.(Buy|Sell)\([^\n]*,[^\n]*,[^\n]*,[^\n]*,[1-9]/);assert.match(s,/noSL=true/)});
test('15 percent then double margin ladder',()=>{assert.match(s,/baseMarginPct=15/);assert.match(s,/layerMultiplier=2/);assert.match(s,/MathPow\(C\.layerMultiplier,layers\)/)});
test('setup is multi-stage not blind fade',()=>{for(const x of ['WATCH_ARMED','rejected','microBreak','CONFIRMED_EXHAUSTION_REVERSAL'])assert.match(s,new RegExp(x))});
test('adds require profit and confirmation',()=>{assert.match(s,/if\(p<=0\)return/);assert.match(s,/continuation\|\|s\.pullbackFail\|\|s\.microBreak/);assert.match(s,/spaced&&earned/)});
test('equity target basket close uses campaign-scoped equity, not raw account equity',()=>{assert.match(s,/campEq>=targetEq/);assert.match(s,/campEq=cycleStart\+p/);assert.match(s,/BASKET_EQUITY_TARGET/)});
test('learning adjustments consumed',()=>{assert.match(s,/learnEntryAdj/);assert.match(s,/learnAddAdj/)});
test('campaign start emits the real feature vector the learning brain needs, not just the score',()=>{assert.match(s,/\\"impulseMult\\":%\.3f/);assert.match(s,/\\"wickRatio\\":%\.3f/);assert.match(s,/\\"m3\\":%s/);assert.match(s,/\\"m5\\":%s/)});
test('rejection zone width is configurable, not a silent magic number',()=>{assert.match(s,/rejectionZoneAtr=\.12/);assert.match(s,/C\.rejectionZoneAtr\*s\.atr/);assert.doesNotMatch(s,/-\.12\*s\.atr/)});
test('restart recovery is magic-number scoped, not a blind PositionSelect guess',()=>{assert.match(s,/NewestMagicPosition/);assert.match(s,/PositionGetInteger\(POSITION_MAGIC\)!=InpMagic/);assert.doesNotMatch(s,/PositionSelect\(_Symbol\)&&PositionGetInteger\(POSITION_TYPE\)/)});
test('restart recovery persists and reloads local state so pyramiding does not silently freeze',()=>{assert.match(s,/SaveState/);assert.match(s,/LoadState/);assert.match(s,/ClearState/)});
test('Strategy Tester can actually run the EA: WebRequest is skipped and it self-arms, instead of spamming ERR_FUNCTION_NOT_ALLOWED forever unarmed',()=>{assert.match(s,/if\(\(bool\)MQLInfoInteger\(MQL_TESTER\)\)return false;/);assert.match(s,/if\(\(bool\)MQLInfoInteger\(MQL_TESTER\)\)C\.armed=true;/)});
