// Generates extracted.h from the REAL .mq5 sources, compiles the scenario driver and
// returns the parsed JSONL. No Apex decision logic is re-implemented here.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readSource, extract } from './extract.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));
const repo=path.resolve(here,'..','..');

const CXX_CANDIDATES=[
  '/Library/Developer/CommandLineTools/usr/bin/c++',
  '/usr/bin/clang++','/usr/bin/g++','c++','g++'
];
export function findCxx(){
  for(const c of CXX_CANDIDATES){
    try{execFileSync(c,['--version'],{stdio:'pipe'});return c}catch{}
  }
  return null;
}

// MQL5 uses the MSVC %I64d/%I64u length modifiers; clang wants %lld/%llu. This is the
// ONLY transformation applied to the extracted source text.
function portFormatSpecifiers(src){
  return src.replace(/%I64d/g,'%lld').replace(/%I64u/g,'%llu');
}

// Xcode.app may be absent while the Command Line Tools SDK is present; xcrun then fails.
export function findSdk(){
  for(const p of ['/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk',
                  '/Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk']){
    try{if(fs.existsSync(p))return p}catch{}
  }
  return null;
}

function portMqlArrays(src){
  return src
    .replace(/MqlRates m1\[\],m3\[\],m5\[\];/g,'std::vector<MqlRates> m1,m3,m5;')
    .replace(/void LiquidityRefs\(MqlRates &m1\[\],int n/g,'void LiquidityRefs(MqlRates *m1,int n')
    .replace(/LiquidityRefs\(m1,ArraySize\(m1\)/g,'LiquidityRefs(m1.data(),(int)m1.size()');
}

export function generateExtractedHeader(){
  // Must be the CANONICAL EA that will actually be promoted/compiled -- never a pinned
  // historical file.  A stale harness certifying a newer release is how the v3.8.0
  // SYMBOL_VOLUME_MAX sizing expectation survived into v3.8.1 unchallenged.
  const cur=readSource(path.join(repo,'ea','XauCloud-Apex.mq5'));
  const old=readSource(path.join(repo,'ea','archive','XauCloud-Apex-v3.7.1.mq5'));

  const structs=[
    extract(cur,'SizingDecision',{kind:'struct'}),
    extract(cur,'Gate',{kind:'struct'}),
    extract(cur,'Setup',{kind:'struct'}),
    extract(cur,'Snap',{kind:'struct'})
  ].join('\n\n');
  const fns=[
    extract(cur,'VolStep'),
    extract(cur,'VolDigits'),
    extract(cur,'FloorToStep'),
    extract(cur,'ResolveFillingMode'),
    extract(cur,'ResetMarketClosedBackoff'),
    extract(cur,'NoteMarketClosed'),
    extract(cur,'MarketClosedBackoffActive'),
    extract(cur,'NotionalPerLot'),
    extract(cur,'MarginPerLotAtLeverage'),
    extract(cur,'LeverageMarginPerLot'),
    extract(cur,'ServerCapacityCeiling'),
    extract(cur,'NoteServerRejectedVolume'),
    extract(cur,'NoteServerFilledVolume'),
    extract(cur,'FixedInitialMarginPerLot'),
    extract(cur,'TrustedMarginPerLot'),
    extract(cur,'BrokerAcceptsVolume'),
    extract(cur,'LargestVolumeWithinMargin'),
    extract(cur,'LargestVolumePassingCheck'),
    extract(cur,'ComputeVolume'),
    extract(cur,'ComputeExecRegion'),
    extract(cur,'PriceInExecRegion'),
    extract(cur,'LiquidityRefs'),
    extract(cur,'RememberDeadThesis'),
    extract(cur,'MaybeClearDeadThesis'),
    extract(cur,'DeadThesisBlocks'),
    extract(cur,'Fnv1a'),
    extract(cur,'NewSetupId'),
    extract(cur,'SetupReset'),
    extract(cur,'ArmSetup'),
    extract(cur,'Observe'),
    extract(cur,'ApplyLegacySchemaGuard'),
    extract(cur,'FinalEntryGate'),
    extract(cur,'IsSizeOnlyRejection')
  ].join('\n\n');
  const currentParts=structs+`

#define APEX_SCORE_BASE 25.0
Setup S;
string g_instanceId="native";
bool g_deadThesisActive=false;
int g_deadThesisDir=0;
double g_deadThesisExtreme=0;
double g_deadThesisPrior=0;
datetime g_deadThesisSweep=0;
datetime g_noRearmBeforeBar=0;
int g_noRearmDir=0;
CampState campState=CAMP_IDLE;
bool anchorsKnown=true;
double campInvalidLevel=0,campOriginHigh=0,campOriginLow=0,campOriginClose=0;
datetime campOriginBar=0;
ApexBosMode InpBosMode=BOS_V371_CLOSE_OR_WICK;
bool InpRequireFreshM3=false;

`+fns;

  // v3.7.1 originals, renamed only so both generations can coexist in one binary.
  let legacy=[extract(old,'VolDigits'),extract(old,'NormVol'),extract(old,'VolumeForMargin')].join('\n\n');
  legacy=legacy
    .replace(/\bVolDigits\b/g,'v371_VolDigits')
    .replace(/\bNormVol\b/g,'v371_NormVol')
    .replace(/\bVolumeForMargin\b/g,'v371_VolumeForMargin');

  const header=
`// GENERATED by tests/native/build_and_run.mjs -- do not edit.
// Function bodies below are extracted VERBATIM from:
//   ea/XauCloud-Apex.mq5        (current)
//   ea/archive/XauCloud-Apex-v3.7.1.mq5 (audited HEAD, renamed v371_*)
// Only %I64d/%I64u -> %lld/%llu was rewritten, for the host printf.

${portFormatSpecifiers(portMqlArrays(currentParts))}

// ------------------------- v3.7.1 originals -------------------------
${portFormatSpecifiers(legacy)}
`;
  return header;
}

export function buildAndRun(){
  const cxx=findCxx();
  if(!cxx)return {skipped:'NO_CXX_TOOLCHAIN',rows:[]};
  const out=fs.mkdtempSync(path.join(os.tmpdir(),'apex-native-'));
  fs.writeFileSync(path.join(here,'extracted.h'),generateExtractedHeader());
  const bin=path.join(out,'apex_native');
  const args=['-std=c++17','-O0','-Wno-format','-Wno-format-security','-Wno-writable-strings',
    '-o',bin,path.join(here,'main.cpp'),'-I',here];
  const sdk=findSdk();
  if(sdk)args.push('-isysroot',sdk);
  execFileSync(cxx,args,{stdio:'pipe'});
  const stdout=execFileSync(bin,[],{encoding:'utf8'});
  const rows=stdout.trim().split('\n').filter(Boolean).map(l=>JSON.parse(l));
  const byName={};for(const r of rows)byName[r.test]=r;
  fs.rmSync(out,{recursive:true,force:true});
  return {skipped:null,rows,byName,stdout};
}
