// GENERATED by tests/native/build_and_run.mjs -- do not edit.
// Function bodies below are extracted VERBATIM from:
//   ea/XauCloud-Apex-v3.8.0.mq5        (current)
//   ea/archive/XauCloud-Apex-v3.7.1.mq5 (audited HEAD, renamed v371_*)
// Only %I64d/%I64u -> %lld/%llu was rewritten, for the host printf.

struct SizingDecision
  {
   double pct,freeMargin,budget;
   double volMin,volMax,volStep;
   double marginAtVolMax,marginAtOneLot,marginAtFinal;
   double capacityByMargin,capacityByBroker,capacity;
   double byCapacityPct,byMarginBudget,requested,finalVolume;
   uint   checkRetcode;
   bool   marginBinding;
   string blockReason;
  };

struct Gate
  {
   bool     ok;
   string   reason;
   double   bid,ask,price,extensionAtr;
   long     quoteAgeMs;
   bool     reclaimed,triggerStale,quoteStale,extended;
  };

double VolStep()
  {
   double st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(st>0) return st;
   double mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   return mn>0?mn:0.01;
  }

int VolDigits()
  {
   double st=VolStep();
   for(int d=0;d<=8;d++)
     {
      double f=MathPow(10.0,d);
      if(MathAbs(st*f-MathRound(st*f))<1e-9) return d;
     }
   return 8;
  }

double FloorToStep(double v)
  {
   double st=VolStep();
   if(st<=0) return 0;
   double n=MathFloor(v/st+1e-9)*st;
   if(n<0) n=0;
   return NormalizeDouble(n,VolDigits());
  }

bool BrokerAcceptsVolume(int dir,double vol,double price,double sl,uint &rc)
  {
   rc=0;
   if(vol<=0) return false;
   MqlTradeRequest rq; MqlTradeCheckResult cr;
   ZeroMemory(rq); ZeroMemory(cr);
   rq.action=TRADE_ACTION_DEAL;
   rq.symbol=_Symbol;
   rq.volume=vol;
   rq.type=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   rq.price=price;
   rq.sl=sl;
   rq.magic=(ulong)InpMagic;
   rq.deviation=80;
   rq.type_filling=ORDER_FILLING_IOC;
   bool ok=OrderCheck(rq,cr);
   rc=cr.retcode;
   if(ok) return true;
   return rc==TRADE_RETCODE_DONE||rc==TRADE_RETCODE_PLACED;
  }

double LargestVolumeWithinMargin(int dir,double price,double money,double hi)
  {
   if(hi<=0||money<=0) return 0;
   ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   double m=0;
   if(OrderCalcMargin(t,_Symbol,hi,price,m)&&m<=money) return FloorToStep(hi);
   double lo=0,up=hi;
   for(int i=0;i<40;i++)
     {
      double mid=(lo+up)/2;
      if(!OrderCalcMargin(t,_Symbol,mid,price,m)||m>money) up=mid; else lo=mid;
     }
   return FloorToStep(lo);
  }

double LargestVolumePassingCheck(int dir,double price,double sl,double hi)
  {
   if(hi<=0) return 0;
   uint rc=0;
   if(BrokerAcceptsVolume(dir,FloorToStep(hi),price,sl,rc)) return FloorToStep(hi);
   double lo=0,up=hi;
   for(int i=0;i<24;i++)
     {
      double mid=FloorToStep((lo+up)/2);
      if(mid<=0){lo=0;break;}
      if(BrokerAcceptsVolume(dir,mid,price,sl,rc)) lo=mid; else up=mid;
     }
   return FloorToStep(lo);
  }

SizingDecision ComputeVolume(int dir,double pct,double price,double sl)
  {
   SizingDecision d;
   d.pct=pct;d.blockReason="";d.checkRetcode=0;d.marginBinding=false;
   d.capacityByMargin=0;d.capacityByBroker=0;d.capacity=0;
   d.byCapacityPct=0;d.byMarginBudget=0;d.requested=0;d.finalVolume=0;
   d.marginAtVolMax=0;d.marginAtOneLot=0;d.marginAtFinal=0;
   d.volMin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   d.volMax=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   d.volStep=VolStep();
   d.freeMargin=AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   if(d.freeMargin<=0){d.blockReason="NO_FREE_MARGIN";return d;}
   if(price<=0){d.blockReason="NO_QUOTE";return d;}

   double reserve=(C.marginReservePct>0)?d.freeMargin*clamp(C.marginReservePct,0,100)/100.0:0.0;
   double spendable=MathMax(0.0,d.freeMargin-reserve);
   d.budget=spendable*clamp(pct,.1,100)/100.0;
   if(d.budget<=0){d.blockReason="ZERO_BUDGET";return d;}

   double hi=d.volMax;
   if(C.maxBasketLots>0)
     {
      double room=C.maxBasketLots-BasketVolume();
      if(room<=0){d.blockReason="BASKET_LOT_CAP_REACHED";return d;}
      hi=MathMin(hi,room);
     }
   ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   if(!OrderCalcMargin(t,_Symbol,d.volMax,price,d.marginAtVolMax)) d.marginAtVolMax=-1;   // diagnostics only
   if(!OrderCalcMargin(t,_Symbol,1.0,price,d.marginAtOneLot)) d.marginAtOneLot=-1;

   d.capacityByMargin=LargestVolumeWithinMargin(dir,price,spendable,hi);
   d.capacityByBroker=LargestVolumePassingCheck(dir,price,sl,d.capacityByMargin);
   d.capacity=d.capacityByBroker;
   d.byCapacityPct=FloorToStep(d.capacity*clamp(pct,.1,100)/100.0);
   d.byMarginBudget=LargestVolumeWithinMargin(dir,price,d.budget,hi);
   // Whichever expression of the SAME percentage rule binds first.
   d.requested=MathMin(d.byCapacityPct,d.byMarginBudget);
   d.marginBinding=(d.byMarginBudget<=d.byCapacityPct+1e-9);

   double v=FloorToStep(d.requested);
   if(v<d.volMin)
     {
      // APEX-AUDIT-009: the broker minimum is used ONLY when it independently fits the
      // budget. It is never rounded up to from an unaffordable request.
      double mmin=0;
      if(!OrderCalcMargin(t,_Symbol,d.volMin,price,mmin)||mmin>d.budget)
        {d.blockReason=StringFormat("MIN_LOT_MARGIN_%.2f_EXCEEDS_BUDGET_%.2f",mmin,d.budget);return d;}
      if(C.maxBasketLots>0&&BasketVolume()+d.volMin>C.maxBasketLots){d.blockReason="BASKET_LOT_CAP_REACHED";return d;}
      v=NormalizeDouble(d.volMin,VolDigits());
     }
   if(v>hi) v=FloorToStep(hi);
   if(v<=0){d.blockReason="VOLUME_ROUNDS_TO_ZERO";return d;}

   if(!OrderCalcMargin(t,_Symbol,v,price,d.marginAtFinal)){d.blockReason="ORDERCALCMARGIN_FAILED";return d;}
   if(C.minMarginLevelPct>0)
     {
      double eq=AccountInfoDouble(ACCOUNT_EQUITY);
      double used=AccountInfoDouble(ACCOUNT_MARGIN)+d.marginAtFinal;
      double lvl=used>0?(eq/used)*100.0:0;
      if(used>0&&lvl<C.minMarginLevelPct)
        {d.blockReason=StringFormat("MARGIN_LEVEL_%.1f_BELOW_%.1f",lvl,C.minMarginLevelPct);return d;}
     }
   // Broker preflight on the EXACT request that is about to be sent.
   if(!BrokerAcceptsVolume(dir,v,price,sl,d.checkRetcode))
     {
      double reduced=LargestVolumePassingCheck(dir,price,sl,v);
      if(reduced<d.volMin||reduced<=0)
        {d.blockReason=StringFormat("ORDERCHECK_%d_NO_EXECUTABLE_VOLUME",d.checkRetcode);return d;}
      v=reduced;
      if(!OrderCalcMargin(t,_Symbol,v,price,d.marginAtFinal)) d.marginAtFinal=-1;
     }
   d.finalVolume=v;
   return d;
  }

bool FinalEntryGate(int dir,double invalidLevel,double refPrice,double atr,
                    datetime triggerBar,bool enforceReclaim,Gate &g)
  {
   g.ok=false;g.reason="";g.bid=0;g.ask=0;g.price=0;g.extensionAtr=0;g.quoteAgeMs=0;
   g.reclaimed=false;g.triggerStale=false;g.quoteStale=false;g.extended=false;

   MqlTick tk;
   if(!SymbolInfoTick(_Symbol,tk)||tk.bid<=0||tk.ask<=0){g.reason="NO_FRESH_QUOTE";return false;}
   g.bid=tk.bid;g.ask=tk.ask;
   g.price=dir>0?tk.ask:tk.bid;
   g.quoteAgeMs=(long)TimeCurrent()*1000-(long)tk.time_msc;
   if(g.quoteAgeMs<0)g.quoteAgeMs=0;

   if(InpMaxQuoteAgeMs>0&&g.quoteAgeMs>InpMaxQuoteAgeMs)
     {g.quoteStale=true;g.reason=StringFormat("STALE_QUOTE_%lldms",g.quoteAgeMs);return false;}

   // The confirming bar must still be the latest closed M1 bar. This is what makes a
   // stored, already-completed candle pattern unable to authorise an entry later.
   if(InpRequireFreshTrigger&&triggerBar>0)
     {
      datetime lastClosed=iTime(_Symbol,PERIOD_M1,1);
      if(lastClosed!=triggerBar)
        {g.triggerStale=true;
         g.reason=StringFormat("TRIGGER_BAR_NO_LONGER_LATEST_%lld_vs_%lld",(long)triggerBar,(long)lastClosed);
         return false;}
     }

   // The setup's OWN rejected extreme is the invalidation level. No invented threshold.
   if(enforceReclaim&&InpRejectReclaimedExtreme&&invalidLevel>0)
     {
      bool reclaimed=(dir<0)?(g.ask>=invalidLevel):(g.bid<=invalidLevel);
      if(reclaimed)
        {g.reclaimed=true;
         g.reason=StringFormat("RECLAIMED_INVALIDATION_LEVEL_%.5f",invalidLevel);
         return false;}
     }

   if(atr>0&&refPrice>0)
     {
      double ext=(dir<0)?(refPrice-g.bid)/atr:(g.ask-refPrice)/atr;
      g.extensionAtr=ext;
      // OWNER DECISION REQUIRED: unvalidated numeric threshold. SHADOW by default --
      // it is measured and reported on every entry, and blocks nothing unless the
      // owner explicitly sets GATE_ENFORCE.
      if(ext>InpMaxEntryExtensionAtr)
        {
         g.extended=true;
         if(InpEntryExtensionMode==GATE_ENFORCE)
           {g.reason=StringFormat("EXTENDED_%.2fATR_BEYOND_TRIGGER",ext);return false;}
        }
     }
   g.ok=true;g.reason="OK";
   return true;
  }

bool IsSizeOnlyRejection(uint rc,int mt5err)
  {
   return rc==TRADE_RETCODE_NO_MONEY||rc==TRADE_RETCODE_INVALID_VOLUME||
          rc==TRADE_RETCODE_LIMIT_VOLUME||mt5err==134/*ERR_NOT_ENOUGH_MONEY*/;
  }

// ------------------------- v3.7.1 originals -------------------------
int v371_VolDigits(){double st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);return st>=1?0:st>=.1?1:st>=.01?2:3;}

double v371_NormVol(double v){double mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),mx=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);if(st<=0)st=mn;v=MathFloor(v/st)*st;return NormalizeDouble(MathMax(mn,MathMin(mx,v)),v371_VolDigits());}

double v371_VolumeForMargin(int dir,double pct){double free=AccountInfoDouble(ACCOUNT_MARGIN_FREE),budget=free*clamp(pct,.1,100)/100.0,mx=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),p=dir>0?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID),m=0;ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;if(free<=0)return 0;if(OrderCalcMargin(t,_Symbol,mx,p,m)&&m<=budget)return v371_NormVol(mx);double lo=0,hi=mx;for(int i=0;i<36;i++){double mid=(lo+hi)/2;if(!OrderCalcMargin(t,_Symbol,mid,p,m)||m>budget)hi=mid;else lo=mid;}double v=v371_NormVol(lo);if(v<mn){if(OrderCalcMargin(t,_Symbol,mn,p,m)&&m<=budget)return v371_NormVol(mn);return 0;}return v;}
