// GENERATED by tests/native/build_and_run.mjs -- do not edit.
// Function bodies below are extracted VERBATIM from:
//   ea/XauCloud-Apex.mq5        (current)
//   ea/archive/XauCloud-Apex-v3.7.1.mq5 (audited HEAD, renamed v371_*)
// Only %I64d/%I64u -> %lld/%llu was rewritten, for the host printf.

struct SizingDecision
  {
   double pct,freeMargin,budget;
   double volMin,volMax,volStep;
   double marginAtVolMax,marginAtOneLot,marginAtFinal;
   double capacityByMargin,capacityByBroker,capacity;
   double byCapacityPct,byMarginBudget,requested,finalVolume;
   double trustedMarginPerLot,leverageMarginPerLot,initialMarginPerLot;
   // v3.8.2 owner-mandated sizing audit trail (see APEX SIZING telemetry contract).
   long   brokerReportedLeverage,configuredNormalReferenceLeverage,effectiveSizingLeverage;
   bool   brokerMarginModelTrusted;
   double moneyCapacity;
   string capacitySource;
   uint   checkRetcode;
   bool   marginBinding,usedMarginFallback;
   string blockReason,sizingModel;
  };

struct Gate
  {
   bool     ok;
   string   reason;
   double   bid,ask,price,extensionAtr;
   long     quoteAgeMs;
   bool     reclaimed,triggerStale,quoteStale,extended;
  };

double VolStep()
  {
   double st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);
   if(st>0) return st;
   double mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   return mn>0?mn:0.01;
  }

int VolDigits()
  {
   double st=VolStep();
   for(int d=0;d<=8;d++)
     {
      double f=MathPow(10.0,d);
      if(MathAbs(st*f-MathRound(st*f))<1e-9) return d;
     }
   return 8;
  }

double FloorToStep(double v)
  {
   double st=VolStep();
   if(st<=0) return 0;
   double n=MathFloor(v/st+1e-9)*st;
   if(n<0) n=0;
   return NormalizeDouble(n,VolDigits());
  }

bool ResolveFillingMode(ENUM_ORDER_TYPE_FILLING &mode)
  {
   long flags=SymbolInfoInteger(_Symbol,SYMBOL_FILLING_MODE);
   if((flags&SYMBOL_FILLING_FOK)==SYMBOL_FILLING_FOK){mode=ORDER_FILLING_FOK;return true;}
   if((flags&SYMBOL_FILLING_IOC)==SYMBOL_FILLING_IOC){mode=ORDER_FILLING_IOC;return true;}
   ENUM_SYMBOL_TRADE_EXECUTION ex=(ENUM_SYMBOL_TRADE_EXECUTION)SymbolInfoInteger(_Symbol,SYMBOL_TRADE_EXEMODE);
   if(ex!=SYMBOL_TRADE_EXECUTION_MARKET){mode=ORDER_FILLING_RETURN;return true;}
   return false;
  }

void ResetMarketClosedBackoff()
  {
   g_marketClosedRetryAt=0;
   g_marketClosedBackoffSec=0;
  }

void NoteMarketClosed(const string operation,uint retcode)
  {
   int next=(g_marketClosedBackoffSec<=0)?5:(g_marketClosedBackoffSec>=15?30:g_marketClosedBackoffSec*2);
   g_marketClosedBackoffSec=next;
   g_marketClosedRetryAt=TimeCurrent()+next;
   PrintFormat("APEX MARKET CLOSED | op=%s retcode=%u | preserving state; retry in %d sec",
               operation,retcode,next);
  }

bool MarketClosedBackoffActive()
  {
   if(g_marketClosedRetryAt<=0) return false;
   if(TimeCurrent()>=g_marketClosedRetryAt) return false;
   return true;
  }

double NotionalPerLot(double price)
  {
   double contract=SymbolInfoDouble(_Symbol,SYMBOL_TRADE_CONTRACT_SIZE);
   string acct=AccountInfoString(ACCOUNT_CURRENCY);
   string profit=SymbolInfoString(_Symbol,SYMBOL_CURRENCY_PROFIT);
   if(contract<=0||price<=0||acct==""||profit==""||acct!=profit) return 0;
   return contract*price;
  }

double MarginPerLotAtLeverage(double price,long lev)
  {
   if(lev<=0) return 0;
   double notional=NotionalPerLot(price);
   if(notional<=0) return 0;
   return notional/(double)lev;
  }

double LeverageMarginPerLot(double price)
  {
   return MarginPerLotAtLeverage(price,AccountInfoInteger(ACCOUNT_LEVERAGE));
  }

double ServerCapacityCeiling()
  {
   if(g_serverRejectedVolume<=0) return 0;
   // Only meaningful while free margin has not grown beyond the level at which the
   // rejection was observed; more money legitimately means more capacity.
   double now=AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   if(g_serverEvidenceFreeMargin>0&&now>g_serverEvidenceFreeMargin*1.05) return 0;
   double ceiling=g_serverRejectedVolume-VolStep();
   if(g_serverFilledVolume>ceiling) ceiling=g_serverFilledVolume;
   return ceiling>0?ceiling:0;
  }

void NoteServerRejectedVolume(double vol)
  {
   if(vol<=0) return;
   if(g_serverRejectedVolume<=0||vol<g_serverRejectedVolume)
     {
      g_serverRejectedVolume=vol;
      g_serverEvidenceFreeMargin=AccountInfoDouble(ACCOUNT_MARGIN_FREE);
      PrintFormat("APEX SERVER CAPACITY EVIDENCE | rejected=%.4f freeMargin=%.2f -> ceiling=%.4f",
                  vol,g_serverEvidenceFreeMargin,ServerCapacityCeiling());
     }
  }

void NoteServerFilledVolume(double vol)
  {
   if(vol>g_serverFilledVolume) g_serverFilledVolume=vol;
  }

double FixedInitialMarginPerLot()
  {
   double m=SymbolInfoDouble(_Symbol,SYMBOL_MARGIN_INITIAL);
   string acct=AccountInfoString(ACCOUNT_CURRENCY);
   string mc=SymbolInfoString(_Symbol,SYMBOL_CURRENCY_MARGIN);
   if(m<=0||acct==""||mc==""||acct!=mc) return 0;
   return m;
  }

double TrustedMarginPerLot(int dir,double price,double &calcM,double &levM,double &initM,bool &fallback)
  {
   ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   calcM=0;levM=LeverageMarginPerLot(price);initM=FixedInitialMarginPerLot();fallback=false;
   double tmp=0;
   if(OrderCalcMargin(t,_Symbol,1.0,price,tmp)&&MathIsValidNumber(tmp)&&tmp>0) calcM=tmp;
   double trusted=MathMax(calcM,MathMax(levM,initM));
   fallback=(trusted>calcM+1e-8);
   return trusted;
  }

bool BrokerAcceptsVolume(int dir,double vol,double price,double sl,uint &rc)
  {
   rc=0;
   if(vol<=0) return false;
   MqlTradeRequest rq; MqlTradeCheckResult cr;
   ZeroMemory(rq); ZeroMemory(cr);
   rq.action=TRADE_ACTION_DEAL;
   rq.symbol=_Symbol;
   rq.volume=vol;
   rq.type=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   rq.price=price;
   rq.sl=sl;
   rq.magic=(ulong)InpMagic;
   rq.deviation=80;
   ENUM_ORDER_TYPE_FILLING filling;
   if(!ResolveFillingMode(filling)){rc=TRADE_RETCODE_INVALID_FILL;return false;}
   rq.type_filling=filling;
   bool ok=OrderCheck(rq,cr);
   rc=cr.retcode;
   if(ok) return true;
   return rc==TRADE_RETCODE_DONE||rc==TRADE_RETCODE_PLACED;
  }

double LargestVolumeWithinMargin(int dir,double price,double money,double hi)
  {
   if(hi<=0||money<=0) return 0;
   ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   double m=0;
   if(OrderCalcMargin(t,_Symbol,hi,price,m)&&m<=money) return FloorToStep(hi);
   double lo=0,up=hi;
   for(int i=0;i<40;i++)
     {
      double mid=(lo+up)/2;
      if(!OrderCalcMargin(t,_Symbol,mid,price,m)||m>money) up=mid; else lo=mid;
     }
   return FloorToStep(lo);
  }

double LargestVolumePassingCheck(int dir,double price,double sl,double hi)
  {
   if(hi<=0) return 0;
   uint rc=0;
   if(BrokerAcceptsVolume(dir,FloorToStep(hi),price,sl,rc)) return FloorToStep(hi);
   if(rc==TRADE_RETCODE_MARKET_CLOSED){NoteMarketClosed("ORDERCHECK",rc);return 0;}
   double lo=0,up=hi;
   for(int i=0;i<24;i++)
     {
      double mid=FloorToStep((lo+up)/2);
      if(mid<=0){lo=0;break;}
      if(BrokerAcceptsVolume(dir,mid,price,sl,rc)) lo=mid;
      else
        {
         if(rc==TRADE_RETCODE_MARKET_CLOSED){NoteMarketClosed("ORDERCHECK",rc);return 0;}
         up=mid;
        }
     }
   return FloorToStep(lo);
  }

SizingDecision ComputeVolume(int dir,double pct,double price,double sl)
  {
   SizingDecision d;
   d.pct=pct;d.blockReason="";d.checkRetcode=0;d.marginBinding=false;d.usedMarginFallback=false;
   d.capacityByMargin=0;d.capacityByBroker=0;d.capacity=0;
   d.byCapacityPct=0;d.byMarginBudget=0;d.requested=0;d.finalVolume=0;
   d.marginAtVolMax=0;d.marginAtOneLot=0;d.marginAtFinal=0;
   d.trustedMarginPerLot=0;d.leverageMarginPerLot=0;d.initialMarginPerLot=0;d.sizingModel="";
   d.brokerReportedLeverage=AccountInfoInteger(ACCOUNT_LEVERAGE);
   d.configuredNormalReferenceLeverage=C.normalReferenceLeverage;
   d.effectiveSizingLeverage=0;d.brokerMarginModelTrusted=false;
   d.moneyCapacity=0;d.capacitySource="";
   d.volMin=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN);
   d.volMax=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX);
   d.volStep=VolStep();
   d.freeMargin=AccountInfoDouble(ACCOUNT_MARGIN_FREE);
   if(d.freeMargin<=0){d.blockReason="NO_FREE_MARGIN";return d;}
   if(price<=0){d.blockReason="NO_QUOTE";return d;}

   double reserve=(C.marginReservePct>0)?d.freeMargin*clamp(C.marginReservePct,0,100)/100.0:0.0;
   double spendable=MathMax(0.0,d.freeMargin-reserve);
   d.budget=spendable*clamp(pct,.1,100)/100.0;
   if(d.budget<=0){d.blockReason="ZERO_BUDGET";return d;}

   double hi=d.volMax;
   if(C.maxBasketLots>0)
     {
      double room=C.maxBasketLots-BasketVolume();
      if(room<=0){d.blockReason="BASKET_LOT_CAP_REACHED";return d;}
      hi=MathMin(hi,room);
     }
   ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;
   if(!OrderCalcMargin(t,_Symbol,d.volMax,price,d.marginAtVolMax)) d.marginAtVolMax=-1;
   if(!OrderCalcMargin(t,_Symbol,1.0,price,d.marginAtOneLot)) d.marginAtOneLot=-1;

   // ================= NORMAL =================================================
   // 15/50/100 are percentages of the CURRENT, genuinely executable margin capacity,
   // recomputed from live free margin on every layer. They are never percentages of
   // the starting balance and never percentages of SYMBOL_VOLUME_MAX.
   //
   // Capacity basis, in order:
   //   A. the broker's own margin economics, when they are trustworthy;
   //   B. the owner-configured NORMAL reference leverage, when the broker/terminal
   //      reports a pathological model (e.g. 1:2000000000 with marginAt1Lot=0);
   //   C. otherwise refuse -- NORMAL_REFERENCE_LEVERAGE_REQUIRED. Never guess.
   //
   // This NEVER selects the profile. accountProfile alone decides NORMAL vs UNLIMITED.
   if(ExecutionProfile()=="NORMAL")
     {
      double calcM=0,levM=0,initM=0;bool fallback=false;
      double brokerMarginPerLot=TrustedMarginPerLot(dir,price,calcM,levM,initM,fallback);
      d.leverageMarginPerLot=levM;d.initialMarginPerLot=initM;d.usedMarginFallback=fallback;
      d.brokerReportedLeverage=AccountInfoInteger(ACCOUNT_LEVERAGE);
      d.configuredNormalReferenceLeverage=C.normalReferenceLeverage;

      // The broker margin model is trustworthy only while MONEY is what limits the
      // size. If it says the account can afford the broker's entire maximum order,
      // then the percentages would silently degrade into "% of SYMBOL_VOLUME_MAX" --
      // which is exactly the defect that sent 30 lots on a $1,000 account.
      double brokerCapacity=(brokerMarginPerLot>0)?spendable/brokerMarginPerLot:0;
      d.brokerMarginModelTrusted=(brokerMarginPerLot>0
                                  &&MathIsValidNumber(brokerMarginPerLot)
                                  &&d.volMax>0&&brokerCapacity<d.volMax);

      if(d.brokerMarginModelTrusted)
        {
         d.trustedMarginPerLot=brokerMarginPerLot;
         d.capacitySource="BROKER_MARGIN";
         d.sizingModel=fallback?"NORMAL_TRUSTED_MARGIN_FALLBACK":"NORMAL_ORDERCALC_MARGIN";
         double notional=NotionalPerLot(price);
         d.effectiveSizingLeverage=(notional>0)?(long)MathRound(notional/brokerMarginPerLot)
                                              :AccountInfoInteger(ACCOUNT_LEVERAGE);
        }
      else if(C.normalReferenceLeverage>0)
        {
         double refM=MarginPerLotAtLeverage(price,C.normalReferenceLeverage);
         if(refM<=0||!MathIsValidNumber(refM))
           {d.blockReason="NORMAL_REFERENCE_LEVERAGE_UNUSABLE_FOR_THIS_SYMBOL";return d;}
         d.trustedMarginPerLot=refM;
         d.capacitySource="NORMAL_REFERENCE_LEVERAGE";
         d.sizingModel="NORMAL_REFERENCE_LEVERAGE";
         d.effectiveSizingLeverage=C.normalReferenceLeverage;
        }
      else
        {
         // AUTO is only legal while the broker model is trustworthy. It is not.
         d.capacitySource="NONE";
         d.blockReason=StringFormat("NORMAL_REFERENCE_LEVERAGE_REQUIRED_BROKER_LEV_%lld_MARGIN1LOT_%.6f",
                                    AccountInfoInteger(ACCOUNT_LEVERAGE),calcM);
         return d;
        }

      d.moneyCapacity=spendable/d.trustedMarginPerLot;
      // SYMBOL_VOLUME_MAX and the owner basket cap are technical ceilings that clamp the
      // result. They are never the denominator the percentage is taken from.
      d.capacity=FloorToStep(MathMin(hi,d.moneyCapacity));
      d.capacityByMargin=d.capacity;
      d.byCapacityPct=FloorToStep(d.capacity*clamp(pct,.1,100)/100.0);
      d.byMarginBudget=FloorToStep(MathMin(hi,d.budget/d.trustedMarginPerLot));
      d.requested=MathMin(d.byCapacityPct,d.byMarginBudget);
      d.marginBinding=true;

      double v=FloorToStep(d.requested);
      if(v<d.volMin)
        {
         double trustedMin=d.trustedMarginPerLot*d.volMin;
         if(trustedMin>d.budget+1e-8)
           {d.blockReason=StringFormat("MIN_LOT_TRUSTED_MARGIN_%.2f_EXCEEDS_BUDGET_%.2f",trustedMin,d.budget);return d;}
         if(C.maxBasketLots>0&&BasketVolume()+d.volMin>C.maxBasketLots){d.blockReason="BASKET_LOT_CAP_REACHED";return d;}
         v=NormalizeDouble(d.volMin,VolDigits());
        }
      if(v>hi) v=FloorToStep(hi);
      if(v<=0){d.blockReason="VOLUME_ROUNDS_TO_ZERO";return d;}

      // Broker preflight on the EXACT intended tier. A rejection here does NOT get
      // halved into a different effective percentage -- see the NORMAL branch of the
      // OpenLayer retry loop, which re-derives capacity and re-applies the SAME pct.
      if(!OrderCalcMargin(t,_Symbol,v,price,d.marginAtFinal)) d.marginAtFinal=-1;
      if(!BrokerAcceptsVolume(dir,v,price,sl,d.checkRetcode))
        {
         if(d.checkRetcode==TRADE_RETCODE_MARKET_CLOSED){NoteMarketClosed("ORDERCHECK",d.checkRetcode);d.blockReason="MARKET_CLOSED_BACKOFF";return d;}
         d.blockReason=StringFormat("NORMAL_ORDERCHECK_%d_REJECTED",d.checkRetcode);
         return d;
        }
      d.capacityByBroker=v; // only the exact intended tier was proven, not an invented max
      if(C.minMarginLevelPct>0&&d.marginAtFinal>0)
        {
         double eq=AccountInfoDouble(ACCOUNT_EQUITY);
         double used=AccountInfoDouble(ACCOUNT_MARGIN)+d.marginAtFinal;
         double lvl=used>0?(eq/used)*100.0:0;
         if(used>0&&lvl<C.minMarginLevelPct)
           {d.blockReason=StringFormat("MARGIN_LEVEL_%.1f_BELOW_%.1f",lvl,C.minMarginLevelPct);return d;}
        }
      d.finalVolume=v;
      return d;
     }

   // UNLIMITED: preserve the owner's aggressive semantics.  It may discover the largest
   // executable size by broker preflight / size-only step-down because 100% capacity is
   // exactly what this profile asks for.
   d.sizingModel="UNLIMITED_BROKER_CAPACITY";
   d.capacitySource="UNLIMITED_SERVER_CAPACITY";
   d.effectiveSizingLeverage=AccountInfoInteger(ACCOUNT_LEVERAGE);
   // v3.8.2: on a broker whose client margin model reports ~0 for gold, both
   // OrderCalcMargin and OrderCheck happily approve SYMBOL_VOLUME_MAX while the trade
   // server answers NO_MONEY. That is the "Apex believed 200 lots was executable" bug.
   // We therefore fold in what the SERVER has actually proven on this account+symbol:
   // any volume at or above a previously server-rejected size is not a real estimate.
   // This is evidence the broker already gave us -- it is not a risk cap, and it never
   // reduces a size the server has actually filled.
   double serverHi=hi;
   double learnedCeiling=ServerCapacityCeiling();
   if(learnedCeiling>0) serverHi=MathMin(serverHi,learnedCeiling);
   d.capacityByMargin=LargestVolumeWithinMargin(dir,price,spendable,serverHi);
   d.capacityByBroker=LargestVolumePassingCheck(dir,price,sl,d.capacityByMargin);
   if(MarketClosedBackoffActive()){d.blockReason="MARKET_CLOSED_BACKOFF";return d;}
   d.capacity=d.capacityByBroker;
   d.moneyCapacity=d.capacity;
   d.byCapacityPct=FloorToStep(d.capacity*clamp(pct,.1,100)/100.0);
   d.byMarginBudget=LargestVolumeWithinMargin(dir,price,d.budget,serverHi);
   d.requested=MathMin(d.byCapacityPct,d.byMarginBudget);
   d.marginBinding=(d.byMarginBudget<=d.byCapacityPct+1e-9);

   double v=FloorToStep(d.requested);
   if(v<d.volMin)
     {
      // APEX-AUDIT-009: the broker minimum is used ONLY when it independently fits the
      // budget. It is never rounded up to from an unaffordable request.
      double mmin=0;
      if(!OrderCalcMargin(t,_Symbol,d.volMin,price,mmin)||mmin>d.budget)
        {d.blockReason=StringFormat("MIN_LOT_MARGIN_%.2f_EXCEEDS_BUDGET_%.2f",mmin,d.budget);return d;}
      if(C.maxBasketLots>0&&BasketVolume()+d.volMin>C.maxBasketLots){d.blockReason="BASKET_LOT_CAP_REACHED";return d;}
      v=NormalizeDouble(d.volMin,VolDigits());
     }
   if(v>hi) v=FloorToStep(hi);
   if(v<=0){d.blockReason="VOLUME_ROUNDS_TO_ZERO";return d;}
   if(!OrderCalcMargin(t,_Symbol,v,price,d.marginAtFinal)) d.marginAtFinal=-1;
   if(!BrokerAcceptsVolume(dir,v,price,sl,d.checkRetcode))
     {
      double reduced=LargestVolumePassingCheck(dir,price,sl,v);
      if(reduced<d.volMin||reduced<=0)
        {d.blockReason=StringFormat("ORDERCHECK_%d_NO_EXECUTABLE_VOLUME",d.checkRetcode);return d;}
      v=reduced;
      if(!OrderCalcMargin(t,_Symbol,v,price,d.marginAtFinal)) d.marginAtFinal=-1;
     }
   // v3.8.2: minMarginLevelPct is an OWNER-CONFIGURED control that existed in v3.8.1 for
   // BOTH profiles.  The CapacityTruth draft moved it inside the NORMAL branch only, which
   // silently removed it from UNLIMITED.  Restored here; when the owner leaves it at 0 this
   // is a no-op, so UNLIMITED stays exactly as aggressive as configured.
   if(C.minMarginLevelPct>0&&d.marginAtFinal>0)
     {
      double eq=AccountInfoDouble(ACCOUNT_EQUITY);
      double used=AccountInfoDouble(ACCOUNT_MARGIN)+d.marginAtFinal;
      double lvl=used>0?(eq/used)*100.0:0;
      if(used>0&&lvl<C.minMarginLevelPct)
        {d.blockReason=StringFormat("MARGIN_LEVEL_%.1f_BELOW_%.1f",lvl,C.minMarginLevelPct);return d;}
     }
   d.finalVolume=v;
   return d;
  }

bool FinalEntryGate(int dir,double invalidLevel,double refPrice,double atr,
                    datetime triggerBar,bool enforceReclaim,Gate &g)
  {
   g.ok=false;g.reason="";g.bid=0;g.ask=0;g.price=0;g.extensionAtr=0;g.quoteAgeMs=0;
   g.reclaimed=false;g.triggerStale=false;g.quoteStale=false;g.extended=false;

   MqlTick tk;
   if(!SymbolInfoTick(_Symbol,tk)||tk.bid<=0||tk.ask<=0){g.reason="NO_FRESH_QUOTE";return false;}
   g.bid=tk.bid;g.ask=tk.ask;
   g.price=dir>0?tk.ask:tk.bid;
   g.quoteAgeMs=(long)TimeCurrent()*1000-(long)tk.time_msc;
   if(g.quoteAgeMs<0)g.quoteAgeMs=0;

   if(InpMaxQuoteAgeMs>0&&g.quoteAgeMs>InpMaxQuoteAgeMs)
     {g.quoteStale=true;g.reason=StringFormat("STALE_QUOTE_%lldms",g.quoteAgeMs);return false;}

   // The confirming bar must still be the latest closed M1 bar. This is what makes a
   // stored, already-completed candle pattern unable to authorise an entry later.
   if(InpRequireFreshTrigger&&triggerBar>0)
     {
      datetime lastClosed=iTime(_Symbol,PERIOD_M1,1);
      if(lastClosed!=triggerBar)
        {g.triggerStale=true;
         g.reason=StringFormat("TRIGGER_BAR_NO_LONGER_LATEST_%lld_vs_%lld",(long)triggerBar,(long)lastClosed);
         return false;}
     }

   // The setup's OWN rejected extreme is the invalidation level. No invented threshold.
   if(enforceReclaim&&InpRejectReclaimedExtreme&&invalidLevel>0)
     {
      bool reclaimed=(dir<0)?(g.ask>=invalidLevel):(g.bid<=invalidLevel);
      if(reclaimed)
        {g.reclaimed=true;
         g.reason=StringFormat("RECLAIMED_INVALIDATION_LEVEL_%.5f",invalidLevel);
         return false;}
     }

   if(atr>0&&refPrice>0)
     {
      double ext=(dir<0)?(refPrice-g.bid)/atr:(g.ask-refPrice)/atr;
      g.extensionAtr=ext;
      // OWNER DECISION REQUIRED: unvalidated numeric threshold. SHADOW by default --
      // it is measured and reported on every entry, and blocks nothing unless the
      // owner explicitly sets GATE_ENFORCE.
      if(ext>InpMaxEntryExtensionAtr)
        {
         g.extended=true;
         if(InpEntryExtensionMode==GATE_ENFORCE)
           {g.reason=StringFormat("EXTENDED_%.2fATR_BEYOND_TRIGGER",ext);return false;}
        }
     }
   g.ok=true;g.reason="OK";
   return true;
  }

bool IsSizeOnlyRejection(uint rc,int mt5err)
  {
   return rc==TRADE_RETCODE_NO_MONEY||rc==TRADE_RETCODE_INVALID_VOLUME||
          rc==TRADE_RETCODE_LIMIT_VOLUME||mt5err==134/*ERR_NOT_ENOUGH_MONEY*/;
  }

// ------------------------- v3.7.1 originals -------------------------
int v371_VolDigits(){double st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);return st>=1?0:st>=.1?1:st>=.01?2:3;}

double v371_NormVol(double v){double mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),mx=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);if(st<=0)st=mn;v=MathFloor(v/st)*st;return NormalizeDouble(MathMax(mn,MathMin(mx,v)),v371_VolDigits());}

double v371_VolumeForMargin(int dir,double pct){double free=AccountInfoDouble(ACCOUNT_MARGIN_FREE),budget=free*clamp(pct,.1,100)/100.0,mx=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),p=dir>0?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID),m=0;ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;if(free<=0)return 0;if(OrderCalcMargin(t,_Symbol,mx,p,m)&&m<=budget)return v371_NormVol(mx);double lo=0,hi=mx;for(int i=0;i<36;i++){double mid=(lo+hi)/2;if(!OrderCalcMargin(t,_Symbol,mid,p,m)||m>budget)hi=mid;else lo=mid;}double v=v371_NormVol(lo);if(v<mn){if(OrderCalcMargin(t,_Symbol,mn,p,m)&&m<=budget)return v371_NormVol(mn);return 0;}return v;}
