// Scenario driver. The Apex logic under test is #included verbatim from the real .mq5
// sources (generated by tests/native/extract.mjs into extracted.h). Emits one JSON
// object per scenario on stdout.
#include "mt5shim.h"
MockBroker  BRK;
ApexConfig  C;
long        InpMagic=8620260903L;
int         InpMaxQuoteAgeMs=0;
bool        InpRequireFreshTrigger=true;
bool        InpRejectReclaimedExtreme=true;
double      InpMaxEntryExtensionAtr=1.50;
ApexGateMode InpEntryExtensionMode=GATE_SHADOW;
datetime    g_marketClosedRetryAt=0;
int         g_marketClosedBackoffSec=0;
double      g_serverRejectedVolume=0, g_serverFilledVolume=0, g_serverEvidenceFreeMargin=0;
#include "extracted.h"

#include <iostream>
static void row(const std::string &s){ std::cout<<s<<"\n"; }
static std::string b(bool v){ return v?"true":"false"; }

static void resetBroker(){
  BRK=MockBroker();
  C=ApexConfig();
  InpMaxQuoteAgeMs=0; InpRequireFreshTrigger=true; InpRejectReclaimedExtreme=true;
  InpMaxEntryExtensionAtr=1.50; InpEntryExtensionMode=GATE_SHADOW;
  g_marketClosedRetryAt=0; g_marketClosedBackoffSec=0;
  g_serverRejectedVolume=0; g_serverFilledVolume=0; g_serverEvidenceFreeMargin=0;
  S=Setup();
  campState=CAMP_IDLE; campDir=0; anchorsKnown=true;
  C.requireM3Confirm=false; C.requireM5Context=false; C.learningEnabled=false;
  C.impulseAtr=1.8; C.sweepAtr=0.05; C.rejectionBars=5; C.watchExpiryMinutes=12;
  C.rejectionZoneAtr=0.12; C.entryScore=70;
  InpBosMode=BOS_V371_CLOSE_OR_WICK; InpRequireFreshM3=false;
}

// Mirrors the retry loop in OpenLayer (halve onto the grid while the rejection is
// size-only). tests/ea_static.test.mjs asserts the real OpenLayer contains this loop.
struct DescentResult { double filled; int attempts; std::vector<double> tried; bool gaveUp; };
static DescentResult descend(int dir,double start){
  DescentResult r; r.filled=0; r.attempts=0; r.gaveUp=false;
  double vol=start;
  for(int i=0;i<10;i++){
    r.tried.push_back(vol); r.attempts++;
    double need=BRK.serverMargin(vol);
    if(need<=BRK.freeMargin+1e-9){ r.filled=vol; return r; }
    uint rc=TRADE_RETCODE_NO_MONEY;
    if(!IsSizeOnlyRejection(rc,0)) break;
    double next=FloorToStep(vol*0.5);
    if(next<BRK.volMin||next<=0){ r.gaveUp=true; return r; }
    vol=next;
  }
  r.gaveUp=true; return r;
}

static void emitSizing(const std::string &name,int dir,double pct,double price,double sl){
  double v371=v371_VolumeForMargin(dir,pct);
  SizingDecision d=ComputeVolume(dir,pct,price,sl);
  row(StringFormat(
    "{\"test\":\"%s\",\"pct\":%.2f,\"volMin\":%.5f,\"volMax\":%.5f,\"volStep\":%.5f,"
    "\"freeMargin\":%.2f,\"marginPerLot\":%.4f,\"v371Volume\":%.5f,\"v380Volume\":%.5f,"
    "\"capacityByMargin\":%.5f,\"capacityByBroker\":%.5f,\"byCapacityPct\":%.5f,"
    "\"byMarginBudget\":%.5f,\"budget\":%.2f,\"block\":\"%s\",\"orderCheckRetcode\":%u,"
    "\"profile\":\"%s\",\"capacitySource\":\"%s\",\"brokerReportedLeverage\":%lld,"
    "\"configuredNormalReferenceLeverage\":%lld,\"effectiveSizingLeverage\":%lld,"
    "\"brokerMarginModelTrusted\":%s,\"moneyCapacity\":%.5f,\"trustedMarginPerLot\":%.5f}",
    name.c_str(),pct,d.volMin,d.volMax,d.volStep,d.freeMargin,BRK.marginPerLot,
    v371,d.finalVolume,d.capacityByMargin,d.capacityByBroker,d.byCapacityPct,
    d.byMarginBudget,d.budget,d.blockReason.c_str(),d.checkRetcode,
    ExecutionProfile().c_str(),d.capacitySource.c_str(),d.brokerReportedLeverage,
    d.configuredNormalReferenceLeverage,d.effectiveSizingLeverage,
    b(d.brokerMarginModelTrusted).c_str(),d.moneyCapacity,d.trustedMarginPerLot));
}

// v3.8.7: mirrors the CURRENT OpenLayer retry -- re-derive the capacity the server's
// rejection proves, then re-apply the SAME percentage. tests/ea_static.test.mjs asserts
// the real OpenLayer contains this shape (and no longer contains vol*0.5).
struct RederiveResult { double filled; int attempts; std::vector<double> tried; bool gaveUp; };
static RederiveResult rederive(int dir,double start,double pct,double sl,int maxAttempts){
  RederiveResult r; r.filled=0; r.attempts=0; r.gaveUp=false;
  double vol=start, step=VolStep();
  for(int i=0;i<maxAttempts;i++){
    r.tried.push_back(vol); r.attempts++;
    if(BRK.serverMargin(vol)<=BRK.freeMargin+1e-9){ r.filled=vol; return r; }
    uint rc=TRADE_RETCODE_NO_MONEY;
    if(!IsSizeOnlyRejection(rc,0)) break;
    NoteServerRejectedVolume(vol);
    if(i>=maxAttempts-1) break;
    double capHi=FloorToStep(vol-step);
    double learned=ServerCapacityCeiling();
    if(learned>0&&learned<capHi) capHi=FloorToStep(learned);
    if(capHi<=0) break;
    double trueCap=LargestVolumePassingCheck(dir,BRK.ask,sl,capHi);
    if(trueCap<=0) trueCap=capHi;
    double next=FloorToStep(trueCap*(pct<0.1?0.1:(pct>100?100:pct))/100.0);
    if(next<BRK.volMin||next<=0||next>=vol){ r.gaveUp=true; return r; }
    vol=next;
  }
  r.gaveUp=true; return r;
}

// The ladder itself, read from the REAL extracted LayerMarginPct().
static void emitLadder(const std::string &name,const char *profile){
  C.accountProfile=profile;
  double p[4];
  for(int i=0;i<4;i++){ layers=i; p[i]=LayerMarginPct(); }
  layers=0;
  row(StringFormat("{\"test\":\"%s\",\"profile\":\"%s\",\"L1\":%.4f,\"L2\":%.4f,\"L3\":%.4f,\"L4\":%.4f}",
                   name.c_str(),profile,p[0],p[1],p[2],p[3]));
}

static void emitGate(const std::string &name,int dir,double invalidLevel,double refPrice,
                     double atr,datetime triggerBar){
  Gate g;
  bool ok=FinalEntryGate(dir,invalidLevel,refPrice,atr,triggerBar,true,g);
  row(StringFormat(
    "{\"test\":\"%s\",\"ok\":%s,\"reason\":\"%s\",\"bid\":%.5f,\"ask\":%.5f,"
    "\"extensionAtr\":%.4f,\"reclaimed\":%s,\"triggerStale\":%s,\"quoteStale\":%s,\"extended\":%s}",
    name.c_str(),b(ok).c_str(),g.reason.c_str(),g.bid,g.ask,g.extensionAtr,
    b(g.reclaimed).c_str(),b(g.triggerStale).c_str(),b(g.quoteStale).c_str(),b(g.extended).c_str()));
}

int main(){
  // ---------- A: the live Exness incident ----------------------------------
  // Client-side margin model reports ZERO margin for gold (Exness unlimited-leverage
  // style). v3.7.1's SYMBOL_VOLUME_MAX shortcut then returns 200.00 lots for a NORMAL
  // L1 "15% probe". Reproduces the 2026-09-07 01:39 / 05:27 / 06:34 rejections.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  emitSizing("live_exness_zero_margin_normal_L1",1,15.0,BRK.ask,BRK.ask-30.0);
  emitSizing("live_exness_zero_margin_normal_L2",1,50.0,BRK.ask,0);
  emitSizing("live_exness_zero_margin_normal_L3",1,100.0,BRK.ask,0);

  // ---------- B: EXACT replay of the 2026-09-08 01:24 demo 476885386 incident ----
  // Verbatim from the terminal's own telemetry:
  //   APEX SIZING | profile=NORMAL layer=L1 pct=15.00 | leverage=1:2000000000
  //   freeMargin=1000.00 | volMax=200.0000 | marginAt1Lot=0.00
  //   capacityByMargin=200.0000 | byCapacityPct=30.0000 | FINAL=30.0000
  // and the broker Journal: "market sell 30 XAUUSDm", then L2 "market sell 100".
  // The broker margin model is pathological, so NORMAL must fall back to the OWNER
  // CONFIGURED reference leverage (1:500 for this account), never to SYMBOL_VOLUME_MAX.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664;
  C.normalReferenceLeverage=500;
  emitSizing("incident_476885386_L1_15pct",-1,15.0,BRK.bid,4451.738);
  BRK.freeMargin=3318.99;
  emitSizing("incident_476885386_L2_50pct",-1,50.0,BRK.bid,0);

  // Same pathological broker, but AUTO (no configured reference leverage): refuse.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664;
  emitSizing("pathological_auto_without_reference_blocks",-1,15.0,BRK.bid,0);

  // ---------- the $1,200 account the owner intends to run next ---------------
  // NORMAL, reference leverage 1:500, gold ~4421.564, 100oz contract.
  // margin/lot = 100*4421.564/500 = 884.31 -> capacity 1.35 lots.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664;
  C.normalReferenceLeverage=500;
  emitSizing("acct1200_ref500_L1",-1,15.0,BRK.bid,0);
  emitSizing("acct1200_ref500_L2",-1,50.0,BRK.bid,0);
  emitSizing("acct1200_ref500_L3",-1,100.0,BRK.bid,0);

  // ---------- reference leverage matrix: 1:100 / 1:200 / 1:500 --------------
  // Same $1,200 and price; only the configured economic leverage differs, so the
  // capacity (and therefore every tier) must scale linearly with it.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=100;
  emitSizing("ref_lev_100_L1",-1,15.0,BRK.bid,0);
  emitSizing("ref_lev_100_L3",-1,100.0,BRK.bid,0);
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=200;
  emitSizing("ref_lev_200_L1",-1,15.0,BRK.bid,0);
  emitSizing("ref_lev_200_L3",-1,100.0,BRK.bid,0);
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=500;
  emitSizing("ref_lev_500_L1",-1,15.0,BRK.bid,0);
  emitSizing("ref_lev_500_L3",-1,100.0,BRK.bid,0);

  // ---------- L4+ must keep adding at 100% of CURRENT capacity -------------
  // Free margin falls as layers open; each add re-reads it. L3, L4 and L5 are all
  // 100% tiers, so each must equal 100% of the capacity available AT THAT MOMENT --
  // decreasing, but never blocked merely for being past L3.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=500;
  BRK.freeMargin=1200.0; emitSizing("layer_ladder_L3_100pct",-1,100.0,BRK.bid,0);
  BRK.freeMargin=800.0;  emitSizing("layer_ladder_L4_100pct",-1,100.0,BRK.bid,0);
  BRK.freeMargin=400.0;  emitSizing("layer_ladder_L5_100pct",-1,100.0,BRK.bid,0);

  // The $20 UNLIMITED live account's reported 1:200000000 leverage, NORMAL profile
  // with no configured reference leverage: refuse rather than guess.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=20.40; BRK.leverage=200000000L;
  emitSizing("degenerate_leverage_normal_refuses",1,15.0,BRK.ask,0);

  // A lowercase profile must NOT fall through to the aggressive path.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  C.accountProfile="normal";
  emitSizing("lowercase_profile_still_normal",1,15.0,BRK.ask,0);

  // A NORMAL account on a SANE broker must ignore the reference leverage entirely.
  resetBroker();
  BRK.marginPerLot=880.2; BRK.freeMargin=10000.0; BRK.volMax=200.0; BRK.leverage=500;
  C.normalReferenceLeverage=100;   // configured, but must NOT be used
  emitSizing("sane_broker_ignores_reference_leverage",1,15.0,BRK.ask,0);

  // ---------- C: UNLIMITED profile must stay aggressive ---------------------
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  C.accountProfile="UNLIMITED";
  emitSizing("unlimited_profile_full_allocation",1,100.0,BRK.ask,0);

  // UNLIMITED on the same degenerate $20 account stays aggressive -- the capacity
  // gate is NORMAL-only and must not quietly neuter the owner's chosen profile.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=20.40; BRK.leverage=200000000L;
  C.accountProfile="UNLIMITED";
  emitSizing("unlimited_degenerate_leverage_stays_aggressive",1,100.0,BRK.ask,0);

  // ---------- ordinary linear-margin account: behaviour must be UNCHANGED ---
  resetBroker();
  BRK.marginPerLot=880.2;   // 1:500, 100oz contract, gold 4401
  BRK.freeMargin=10000.0; BRK.volMax=200.0;
  emitSizing("linear_margin_1to500_L1_unchanged",1,15.0,BRK.ask,0);
  emitSizing("linear_margin_1to500_L2_unchanged",1,50.0,BRK.ask,0);
  emitSizing("linear_margin_1to500_L3_unchanged",1,100.0,BRK.ask,0);

  // ---------- APEX-AUDIT-009: minimum lot must not exceed the budget --------
  resetBroker();
  BRK.volMin=0.1; BRK.volStep=0.1; BRK.marginPerLot=100.0; BRK.freeMargin=10.0; BRK.volMax=200.0;
  emitSizing("min_lot_margin_exceeds_budget",1,15.0,BRK.ask,0);

  // ---------- non-decimal / quarter volume steps ---------------------------
  resetBroker();
  BRK.volMin=0.25; BRK.volStep=0.25; BRK.marginPerLot=100.0; BRK.freeMargin=1000.0; BRK.volMax=50.0;
  emitSizing("quarter_volume_step",1,100.0,BRK.ask,0);
  row(StringFormat("{\"test\":\"vol_digits_quarter_step\",\"v380Digits\":%d,\"v371Digits\":%d}",
                   VolDigits(),v371_VolDigits()));
  resetBroker();
  BRK.volMin=0.00125; BRK.volStep=0.00125; BRK.marginPerLot=100.0; BRK.freeMargin=1000.0; BRK.volMax=50.0;
  emitSizing("nondecimal_volume_step",1,100.0,BRK.ask,0);
  row(StringFormat("{\"test\":\"vol_digits_nondecimal_step\",\"v380Digits\":%d,\"v371Digits\":%d}",
                   VolDigits(),v371_VolDigits()));

  // ---------- owner exposure controls are OFF by default -------------------
  resetBroker();
  BRK.marginPerLot=880.2; BRK.freeMargin=10000.0;
  double withoutCaps=ComputeVolume(1,100.0,BRK.ask,0).finalVolume;
  C.maxBasketLots=2.0;
  double withCap=ComputeVolume(1,100.0,BRK.ask,0).finalVolume;
  row(StringFormat("{\"test\":\"owner_caps_opt_in\",\"defaultVolume\":%.5f,\"cappedVolume\":%.5f}",
                   withoutCaps,withCap));

  // ---------- B: broker rejects the size the client model approved ---------
  // The terminal's margin model reports zero margin for gold, so OrderCalcMargin AND
  // OrderCheck both approve. The SERVER still charges 880.2/lot, so only the real
  // submission fails -- exactly the "[No money]" shape seen on the demo account.
  resetBroker();
  BRK.marginPerLot=0.0;            // client model: gold is margin-free
  BRK.serverMarginPerLot=880.2;    // broker truth: 1:500 on a 100oz contract at 4401
  BRK.volMax=200.0; BRK.freeMargin=1000.0;
  {
    SizingDecision d371;
    double v371=v371_VolumeForMargin(1,15.0);
    SizingDecision d=ComputeVolume(1,15.0,BRK.ask,0);
    DescentResult old=descend(1,v371);
    DescentResult neu=descend(1,d.finalVolume);
    std::string tried;
    for(size_t i=0;i<neu.tried.size();i++) tried+=(i?",":"")+StringFormat("%.5f",neu.tried[i]);
    row(StringFormat("{\"test\":\"broker_rejects_client_approved_size\",\"v371Volume\":%.5f,"
                     "\"v380InitialVolume\":%.5f,\"attempts\":%d,\"tried\":[%s],"
                     "\"filledVolume\":%.5f,\"gaveUp\":%s,\"serverAffordable\":%.5f,"
                     "\"v371AttemptsToFill\":%d,\"v371Filled\":%.5f}",
                     v371,d.finalVolume,neu.attempts,tried.c_str(),neu.filled,
                     b(neu.gaveUp).c_str(),BRK.freeMargin/880.2,old.attempts,old.filled));
  }

  // ---------- APEX-AUDIT-001: final executable-price eligibility ------------
  // Same closed bars, three different live quotes. Sell setup: swept high 4410,
  // structural trigger close 4400, ATR 2.0.
  resetBroker();
  BRK.lastClosedM1=1000000;
  BRK.now=1000030;
  BRK.bid=4399.0; BRK.ask=4399.1;
  emitGate("gate_in_zone_quote",-1,4410.0,4400.0,2.0,1000000);
  BRK.bid=4411.0; BRK.ask=4411.1;             // price reclaimed the rejected high
  emitGate("gate_reclaimed_extreme",-1,4410.0,4400.0,2.0,1000000);
  BRK.bid=4390.0; BRK.ask=4390.1;             // 5 ATR beyond the trigger = chasing
  emitGate("gate_extended_chase_shadow",-1,4410.0,4400.0,2.0,1000000);
  InpEntryExtensionMode=GATE_ENFORCE;
  emitGate("gate_extended_chase_enforced",-1,4410.0,4400.0,2.0,1000000);
  InpEntryExtensionMode=GATE_SHADOW;
  BRK.bid=4399.0; BRK.ask=4399.1;
  BRK.lastClosedM1=1000060;                    // a newer bar has closed since the trigger
  emitGate("gate_stale_trigger_bar",-1,4410.0,4400.0,2.0,1000000);
  BRK.lastClosedM1=1000000;
  InpMaxQuoteAgeMs=1500;
  BRK.quoteMsc=(long)(BRK.now-10)*1000;        // 10s-old tick
  emitGate("gate_stale_quote",-1,4410.0,4400.0,2.0,1000000);
  BRK.quoteMsc=0; InpMaxQuoteAgeMs=0;
  InpRejectReclaimedExtreme=false;
  BRK.bid=4411.0; BRK.ask=4411.1;
  emitGate("gate_reclaim_check_disabled",-1,4410.0,4400.0,2.0,1000000);

  // Reclaim of campaign invalidation still blocks (v3.8.2 gate, not origin-box)
  resetBroker();
  BRK.lastClosedM1=1000000; BRK.now=1000030;
  BRK.bid=4411.0; BRK.ask=4411.1;
  emitGate("gate_add_blocked_after_invalidation_reclaim",-1,4410.0,4385.0,2.0,1000000);

  // v3.8.6: WAF HTML 403 is transport; authenticated XauCloud JSON envelope is denial
  resetBroker();
  {
    bool html=BodyLooksLikeJsonObject("<html>cloudflare 403</html>");
    bool empty=BodyLooksLikeJsonObject("   ");
    bool json=BodyLooksLikeJsonObject(" {\"ok\":false}");
    bool waf=IsXauCloudDenialEnvelope(true,"","","",false,true);
    bool denied=IsXauCloudDenialEnvelope(true,"LICENSE_DENIED","","",true,false);
    bool expired=IsXauCloudDenialEnvelope(true,"EXPIRED","","LICENSE_EXPIRED",true,false);
    bool active=IsXauCloudDenialEnvelope(true,"ACTIVE","","",true,true);
    row(StringFormat("{\"test\":\"waf_vs_license_envelope\",\"htmlIsJson\":%s,\"emptyIsJson\":%s,\"jsonObj\":%s,"
                     "\"wafDenied\":%s,\"licenseDenied\":%s,\"expiredDenied\":%s,\"activeDenied\":%s}",
                     b(html).c_str(),b(empty).c_str(),b(json).c_str(),
                     b(waf).c_str(),b(denied).c_str(),b(expired).c_str(),b(active).c_str()));
  }

  // v3.8.5: PLACED is pending (2), fill is 1, other is reject (0)
  resetBroker();
  {
    int filled=ClassifyBrokerSubmit(TRADE_RETCODE_DONE,true);
    int placed=ClassifyBrokerSubmit(TRADE_RETCODE_PLACED,false);
    int placedButFilled=ClassifyBrokerSubmit(TRADE_RETCODE_PLACED,true);
    int nomoney=ClassifyBrokerSubmit(TRADE_RETCODE_NO_MONEY,false);
    row(StringFormat("{\"test\":\"placed_is_pending_not_reject\",\"filled\":%d,\"placed\":%d,\"placedButFilled\":%d,\"nomoney\":%d}",
                     filled,placed,placedButFilled,nomoney));
  }

  // v3.8.5: cross-terminal lease fencing. Network loss never opens a second manager.
  resetBroker();
  {
    datetime now=1'700'000'000;
    bool noCloud=ManagerAllowsNewExposure("A","",(datetime)0,now,false,false);
    bool weHold=ManagerAllowsNewExposure("A","A",now+30,now,true,true);
    bool otherHolds=ManagerAllowsNewExposure("B","A",now+30,now,true,false);
    bool expiredWeWere=ManagerAllowsNewExposure("A","A",now-1,now,true,true);
    bool partitionEmpty=ManagerAllowsNewExposure("A","",now+30,now,true,false);
    bool partitionWeWere=ManagerAllowsNewExposure("A","",now+30,now,true,true);
    row(StringFormat("{\"test\":\"cross_terminal_lease\",\"noCloudAllows\":%s,\"weHold\":%s,\"otherHolds\":%s,"
                     "\"expiredBlocked\":%s,\"partitionWithoutPriorBlocked\":%s,\"partitionWithPriorUntilOk\":%s}",
                     b(noCloud).c_str(),b(weHold).c_str(),b(otherHolds).c_str(),
                     b(!expiredWeWere).c_str(),b(!partitionEmpty).c_str(),b(partitionWeWere).c_str()));
  }

  // v3.8.5: restart-while-confirmed snapshot restore; expired / reclaimed refused
  resetBroker();
  {
    datetime now=1'700'000'000;
    bool watching=SetupSnapshotValidToRestore(SETUP_WATCHING,-1,0,now-60,now,12,4410.0,false);
    bool confirmed=SetupSnapshotValidToRestore(SETUP_CONFIRMED,-1,now-30,now-600,now,12,4410.0,false);
    bool expiredWatch=SetupSnapshotValidToRestore(SETUP_WATCHING,-1,0,now-13*60,now,12,4410.0,false);
    bool expiredFromArmedNotConfirm=SetupSnapshotValidToRestore(SETUP_CONFIRMED,-1,now-30,now-13*60,now,12,4410.0,false);
    bool reclaimed=SetupSnapshotValidToRestore(SETUP_CONFIRMED,-1,now-30,now-60,now,12,4410.0,true);
    bool idle=SetupSnapshotValidToRestore(SETUP_NONE,-1,now-30,now-60,now,12,4410.0,false);
    row(StringFormat("{\"test\":\"restart_while_confirmed\",\"watchingOk\":%s,\"confirmedOk\":%s,"
                     "\"expiredWatchBlocked\":%s,\"confirmedUsesConfirmedAt\":%s,\"reclaimedBlocked\":%s,\"idleBlocked\":%s}",
                     b(watching).c_str(),b(confirmed).c_str(),
                     b(!expiredWatch).c_str(),b(expiredFromArmedNotConfirm).c_str(),
                     b(!reclaimed).c_str(),b(!idle).c_str()));
  }

  // ---------- v3.8.7 UnifiedMarginLadder ------------------------------------
  // (1) One ladder for BOTH profiles, read from the real LayerMarginPct().
  resetBroker(); emitLadder("ladder_normal","NORMAL");
  resetBroker(); emitLadder("ladder_unlimited","UNLIMITED");

  // (2) The percentage is of CURRENT capacity, re-derived per layer. A sane broker with
  // 100.00/lot and 2500 free margin is exactly 25.00 lots of capacity.
  // L1 15% of 25.00 = 3.75. Then capacity genuinely shrinks and L2/L3 must use the NEW
  // number, never the original 25.
  for(const char *prof : {"NORMAL","UNLIMITED"}){
    resetBroker();
    C.accountProfile=prof; C.normalReferenceLeverage=0;
    BRK.marginPerLot=100.0; BRK.volMax=200.0; BRK.freeMargin=2500.0;
    emitSizing(std::string("ladder_capacity_L1_")+prof,1,15.0,BRK.ask,0);
    BRK.freeMargin=2125.0;   // 21.25 lots remain
    emitSizing(std::string("ladder_capacity_L2_")+prof,1,50.0,BRK.ask,0);
    BRK.freeMargin=1063.0;   // 10.63 lots remain
    emitSizing(std::string("ladder_capacity_L3_")+prof,1,100.0,BRK.ask,0);
    BRK.freeMargin=4000.0;   // floating profit created NEW capacity: 40.00 lots
    emitSizing(std::string("ladder_capacity_L4_")+prof,1,100.0,BRK.ask,0);
  }

  // (3) Broker volume steps must never round exposure UP past the percentage budget.
  for(double st : {0.01,0.1,0.25}){
    resetBroker();
    C.accountProfile="UNLIMITED";
    BRK.marginPerLot=100.0; BRK.volMax=200.0; BRK.freeMargin=2500.0; BRK.volStep=st;
    BRK.volMin=st;
    emitSizing(StringFormat("ladder_step_%.2f",st),1,15.0,BRK.ask,0);
  }

  // (4) SIZE-REJECTION REGRESSION. The client model says gold is margin-free, so both
  // OrderCalcMargin and OrderCheck approve SYMBOL_VOLUME_MAX (200). The SERVER charges
  // 100/lot against 2500 free margin, so genuine capacity is 25.00 lots.
  // Pre-3.8.7 UNLIMITED: 15% of a believed 200 = 30 -> rejected -> halve -> 15 -> fills.
  // 15 lots is 60% of the true capacity, not 15%. That must be dead.
  {
    resetBroker();
    C.accountProfile="UNLIMITED";
    BRK.marginPerLot=0.0; BRK.serverMarginPerLot=100.0;
    BRK.volMax=200.0; BRK.freeMargin=2500.0;
    SizingDecision d=ComputeVolume(1,15.0,BRK.ask,0);
    double requested=d.finalVolume;
    DescentResult oldWay=descend(1,requested);
    g_serverRejectedVolume=0; g_serverFilledVolume=0; g_serverEvidenceFreeMargin=0;
    RederiveResult newWay=rederive(1,requested,15.0,0,6);
    std::string tried;
    for(size_t i=0;i<newWay.tried.size();i++) tried+=(i?",":"")+StringFormat("%.5f",newWay.tried[i]);
    row(StringFormat("{\"test\":\"unlimited_size_rejection_preserves_pct\",\"requested\":%.5f,"
                     "\"trueCapacity\":%.5f,\"oldHalvedFill\":%.5f,\"newFill\":%.5f,"
                     "\"newTried\":[%s],\"newAttempts\":%d,\"learnedCeiling\":%.5f}",
                     requested,BRK.freeMargin/BRK.serverMarginPerLot,oldWay.filled,newWay.filled,
                     tried.c_str(),newWay.attempts,ServerCapacityCeiling()));
  }
  // (5) Same shape at L2 = 50%.
  {
    resetBroker();
    C.accountProfile="UNLIMITED";
    BRK.marginPerLot=0.0; BRK.serverMarginPerLot=100.0;
    BRK.volMax=200.0; BRK.freeMargin=2500.0;
    SizingDecision d=ComputeVolume(1,50.0,BRK.ask,0);
    DescentResult oldWay=descend(1,d.finalVolume);
    g_serverRejectedVolume=0; g_serverFilledVolume=0; g_serverEvidenceFreeMargin=0;
    RederiveResult newWay=rederive(1,d.finalVolume,50.0,0,6);
    row(StringFormat("{\"test\":\"unlimited_size_rejection_preserves_pct_L2\",\"requested\":%.5f,"
                     "\"trueCapacity\":%.5f,\"oldHalvedFill\":%.5f,\"newFill\":%.5f}",
                     d.finalVolume,BRK.freeMargin/BRK.serverMarginPerLot,oldWay.filled,newWay.filled));
  }
  // (6) Server evidence tightens the FIRST request of the next campaign -- this is the
  // value of persisting it across a restart.
  {
    resetBroker();
    C.accountProfile="UNLIMITED";
    BRK.marginPerLot=0.0; BRK.serverMarginPerLot=100.0;
    BRK.volMax=200.0; BRK.freeMargin=2500.0;
    SizingDecision cold=ComputeVolume(1,15.0,BRK.ask,0);
    // restart WITHOUT persistence: evidence is zero again -> same oversized request
    g_serverRejectedVolume=0; g_serverFilledVolume=0; g_serverEvidenceFreeMargin=0;
    SizingDecision amnesiac=ComputeVolume(1,15.0,BRK.ask,0);
    // restart WITH persistence: the proven ceiling is restored from state
    g_serverRejectedVolume=30.0; g_serverEvidenceFreeMargin=2500.0; g_serverFilledVolume=0;
    SizingDecision warm=ComputeVolume(1,15.0,BRK.ask,0);
    row(StringFormat("{\"test\":\"capacity_evidence_restart\",\"cold\":%.5f,\"amnesiac\":%.5f,"
                     "\"warm\":%.5f,\"ceiling\":%.5f}",
                     cold.finalVolume,amnesiac.finalVolume,warm.finalVolume,ServerCapacityCeiling()));
  }

  return 0;
}
