// Scenario driver. The Apex logic under test is #included verbatim from the real .mq5
// sources (generated by tests/native/extract.mjs into extracted.h). Emits one JSON
// object per scenario on stdout.
#include "mt5shim.h"
MockBroker  BRK;
ApexConfig  C;
long        InpMagic=8620260903L;
int         InpMaxQuoteAgeMs=0;
bool        InpRequireFreshTrigger=true;
bool        InpRejectReclaimedExtreme=true;
double      InpMaxEntryExtensionAtr=1.50;
ApexGateMode InpEntryExtensionMode=GATE_SHADOW;
datetime    g_marketClosedRetryAt=0;
int         g_marketClosedBackoffSec=0;
double      g_serverRejectedVolume=0, g_serverFilledVolume=0, g_serverEvidenceFreeMargin=0;
#include "extracted.h"

#include <iostream>
static void row(const std::string &s){ std::cout<<s<<"\n"; }
static std::string b(bool v){ return v?"true":"false"; }

static void resetBroker(){
  BRK=MockBroker();
  C=ApexConfig();
  InpMaxQuoteAgeMs=0; InpRequireFreshTrigger=true; InpRejectReclaimedExtreme=true;
  InpMaxEntryExtensionAtr=1.50; InpEntryExtensionMode=GATE_SHADOW;
  g_marketClosedRetryAt=0; g_marketClosedBackoffSec=0;
  g_serverRejectedVolume=0; g_serverFilledVolume=0; g_serverEvidenceFreeMargin=0;
  S=Setup();
  campState=CAMP_IDLE; campDir=0; anchorsKnown=true;
  C.requireM3Confirm=false; C.requireM5Context=false; C.learningEnabled=false;
  C.impulseAtr=1.8; C.sweepAtr=0.05; C.rejectionBars=5; C.watchExpiryMinutes=12;
  C.rejectionZoneAtr=0.12; C.entryScore=70;
  InpBosMode=BOS_V371_CLOSE_OR_WICK; InpRequireFreshM3=false;
}

// Mirrors the retry loop in OpenLayer (halve onto the grid while the rejection is
// size-only). tests/ea_static.test.mjs asserts the real OpenLayer contains this loop.
struct DescentResult { double filled; int attempts; std::vector<double> tried; bool gaveUp; };
static DescentResult descend(int dir,double start){
  DescentResult r; r.filled=0; r.attempts=0; r.gaveUp=false;
  double vol=start;
  for(int i=0;i<10;i++){
    r.tried.push_back(vol); r.attempts++;
    double need=BRK.serverMargin(vol);
    if(need<=BRK.freeMargin+1e-9){ r.filled=vol; return r; }
    uint rc=TRADE_RETCODE_NO_MONEY;
    if(!IsSizeOnlyRejection(rc,0)) break;
    double next=FloorToStep(vol*0.5);
    if(next<BRK.volMin||next<=0){ r.gaveUp=true; return r; }
    vol=next;
  }
  r.gaveUp=true; return r;
}

static void emitSizing(const std::string &name,int dir,double pct,double price,double sl){
  double v371=v371_VolumeForMargin(dir,pct);
  SizingDecision d=ComputeVolume(dir,pct,price,sl);
  row(StringFormat(
    "{\"test\":\"%s\",\"pct\":%.2f,\"volMin\":%.5f,\"volMax\":%.5f,\"volStep\":%.5f,"
    "\"freeMargin\":%.2f,\"marginPerLot\":%.4f,\"v371Volume\":%.5f,\"v380Volume\":%.5f,"
    "\"capacityByMargin\":%.5f,\"capacityByBroker\":%.5f,\"byCapacityPct\":%.5f,"
    "\"byMarginBudget\":%.5f,\"budget\":%.2f,\"block\":\"%s\",\"orderCheckRetcode\":%u,"
    "\"profile\":\"%s\",\"capacitySource\":\"%s\",\"brokerReportedLeverage\":%lld,"
    "\"configuredNormalReferenceLeverage\":%lld,\"effectiveSizingLeverage\":%lld,"
    "\"brokerMarginModelTrusted\":%s,\"moneyCapacity\":%.5f,\"trustedMarginPerLot\":%.5f}",
    name.c_str(),pct,d.volMin,d.volMax,d.volStep,d.freeMargin,BRK.marginPerLot,
    v371,d.finalVolume,d.capacityByMargin,d.capacityByBroker,d.byCapacityPct,
    d.byMarginBudget,d.budget,d.blockReason.c_str(),d.checkRetcode,
    ExecutionProfile().c_str(),d.capacitySource.c_str(),d.brokerReportedLeverage,
    d.configuredNormalReferenceLeverage,d.effectiveSizingLeverage,
    b(d.brokerMarginModelTrusted).c_str(),d.moneyCapacity,d.trustedMarginPerLot));
}

// The ladder itself, read from the REAL extracted LayerMarginPct().
static void emitLadder(const std::string &name,const char *profile){
  C.accountProfile=profile;
  double p[4];
  for(int i=0;i<4;i++){ layers=i; p[i]=LayerMarginPct(); }
  layers=0;
  row(StringFormat("{\"test\":\"%s\",\"profile\":\"%s\",\"L1\":%.4f,\"L2\":%.4f,\"L3\":%.4f,\"L4\":%.4f}",
                   name.c_str(),profile,p[0],p[1],p[2],p[3]));
}

static void emitGate(const std::string &name,int dir,double invalidLevel,double refPrice,
                     double atr,datetime triggerBar){
  Gate g;
  bool ok=FinalEntryGate(dir,invalidLevel,refPrice,atr,triggerBar,true,g);
  row(StringFormat(
    "{\"test\":\"%s\",\"ok\":%s,\"reason\":\"%s\",\"bid\":%.5f,\"ask\":%.5f,"
    "\"extensionAtr\":%.4f,\"reclaimed\":%s,\"triggerStale\":%s,\"quoteStale\":%s,\"extended\":%s}",
    name.c_str(),b(ok).c_str(),g.reason.c_str(),g.bid,g.ask,g.extensionAtr,
    b(g.reclaimed).c_str(),b(g.triggerStale).c_str(),b(g.quoteStale).c_str(),b(g.extended).c_str()));
}

//=============== v3.8.8 UnlimitedFromL3 ======================================
// Everything below drives the REAL extracted PlanLayerSizing / ComputeLayerVolume /
// ComputeSimulated1200Volume / ComputeVolume / RederiveAfterSizeRejection.
static const char *modeOf(const LayerSizingPlan &p){ return p.mode.c_str(); }

// Marks every open position to `price` on a broker whose REAL margin model is
// `lev` (0 = the Exness client model: gold is margin-free). Keeps equity, used
// margin and free margin mutually consistent, exactly as a terminal would report them.
static void markTo(double price,double lev){
  BRK.bid=price; BRK.ask=price;
  BRK.marginPerLot=(lev>0)?price*BRK.contract/lev:0.0;
  double pl=0,vol=0;
  for(auto &p:BRK.positions){ pl+=(p.type==0?1.0:-1.0)*p.volume*BRK.contract*(price-p.open); vol+=p.volume; }
  BRK.equity=BRK.balance+pl;
  BRK.usedMargin=vol*BRK.marginPerLot;
  BRK.freeMargin=BRK.equity-BRK.usedMargin;
  BRK.basketVolume=vol;
}
static void fillPos(int type,double vol,double price){
  BRK.positions.push_back(MockPos{"XAUUSDm",InpMagic,type,vol,price});
}
static double openVolume(){ double v=0; for(auto &p:BRK.positions) v+=p.volume; return v; }

// One layer, sized exactly as OpenLayer() sizes it. Also records what the pre-3.8.8
// engine (ComputeVolume at the same percentage) and the raw UNLIMITED engine at 100%
// would have produced at this instant, so a test can prove which one was NOT used.
static void emitLayer(const std::string &name,int filled,int dir,double sl=0){
  layers=filled;
  double price=dir>0?BRK.ask:BRK.bid;
  LayerSizingPlan plan=PlanLayerSizing(ExecutionProfile(),filled);
  SizingDecision d=ComputeLayerVolume(plan,dir,price,sl);
  SizingDecision oldSamePct=ComputeVolume(dir,plan.pct,price,sl);
  SizingDecision unl100=ComputeVolume(dir,100.0,price,sl);
  row(StringFormat(
    "{\"test\":\"%s\",\"profile\":\"%s\",\"filledLayers\":%d,\"layerIndex\":%d,\"mode\":\"%s\",\"pct\":%.4f,"
    "\"planSimLeverage\":%lld,\"sizingMode\":\"%s\",\"sizingModel\":\"%s\",\"capacitySource\":\"%s\","
    "\"simulatedLeverage\":%lld,\"effectiveSizingLeverage\":%lld,\"price\":%.5f,\"dir\":%d,"
    "\"equity\":%.4f,\"freeMargin\":%.4f,\"usedMargin\":%.4f,\"openVolume\":%.5f,"
    "\"simMarginPerLot\":%.6f,\"simFormulaMarginPerLot\":%.6f,\"simBrokerMarginPerLot\":%.6f,\"simMarginRate\":%.6f,"
    "\"simUsedMargin\":%.6f,\"simFreeMargin\":%.6f,\"simMoneyCapacity\":%.6f,"
    "\"capacityByMargin\":%.5f,\"capacityByBroker\":%.5f,\"capacity\":%.5f,\"targetVolume\":%.6f,"
    "\"requested\":%.5f,\"final\":%.5f,\"block\":\"%s\",\"orderCheckRetcode\":%u,\"volumeLimitRoom\":%.5f,"
    "\"oldEngineSamePctFinal\":%.5f,\"unlimitedCapacityNow\":%.5f,\"unlimited100Final\":%.5f,"
    "\"configuredNormalReferenceLeverage\":%lld}",
    name.c_str(),plan.profile.c_str(),plan.filledLayers,plan.layerIndex,modeOf(plan),plan.pct,
    plan.simulatedLeverage,d.sizingMode.c_str(),d.sizingModel.c_str(),d.capacitySource.c_str(),
    d.simulatedLeverage,d.effectiveSizingLeverage,price,dir,
    BRK.equity,BRK.freeMargin,BRK.usedMargin,openVolume(),
    d.simMarginPerLot,d.simFormulaMarginPerLot,d.simBrokerMarginPerLot,d.simMarginRate,
    d.simUsedMargin,d.simFreeMargin,d.simMoneyCapacity,
    d.capacityByMargin,d.capacityByBroker,d.capacity,d.targetVolume,
    d.requested,d.finalVolume,d.blockReason.c_str(),d.checkRetcode,d.volumeLimitRoom,
    oldSamePct.finalVolume,unl100.capacity,unl100.finalVolume,d.configuredNormalReferenceLeverage));
}

// Mirrors the OpenLayer() retry loop shape; the re-derivation itself is the REAL
// extracted RederiveAfterSizeRejection(). tests/ea_static.test.mjs asserts OpenLayer
// calls it with the SAME plan. `rejectAbove` is an artificial server refusal.
static double g_rejectAbove=0;
static bool serverAccepts(double vol){
  if(g_rejectAbove>0&&vol>g_rejectAbove+1e-9) return false;
  return BRK.serverMargin(vol)<=BRK.freeMargin+1e-9;
}
static void emitRetry(const std::string &name,int filled,int dir,int maxAttempts=10){
  layers=filled;
  double price=dir>0?BRK.ask:BRK.bid;
  LayerSizingPlan plan=PlanLayerSizing(ExecutionProfile(),filled);
  SizingDecision d=ComputeLayerVolume(plan,dir,price,0);
  double vol=d.finalVolume, filledVol=0; bool gaveUp=false; int attempts=0;
  std::string tried, caps;
  for(int i=0;i<maxAttempts&&vol>0;i++){
    tried+=(i?",":"")+StringFormat("%.5f",vol); attempts++;
    if(serverAccepts(vol)){ filledVol=vol; break; }
    NoteServerRejectedVolume(vol);
    if(i>=maxAttempts-1){ gaveUp=true; break; }
    double trueCap=0;
    double next=RederiveAfterSizeRejection(plan,dir,price,0,vol,trueCap);
    caps+=(caps.empty()?"":",")+StringFormat("%.5f",trueCap);
    if(next<=0){ gaveUp=true; break; }
    vol=next;
  }
  // Plan after the retry: the retry never changes the layer count, so never the mode.
  LayerSizingPlan after=PlanLayerSizing(ExecutionProfile(),layers);
  row(StringFormat(
    "{\"test\":\"%s\",\"mode\":\"%s\",\"pct\":%.4f,\"initialCapacity\":%.5f,\"initial\":%.5f,"
    "\"tried\":[%s],\"reDerivedCapacities\":[%s],\"filled\":%.5f,\"attempts\":%d,\"gaveUp\":%s,"
    "\"modeAfter\":\"%s\",\"pctAfter\":%.4f,\"learnedCeiling\":%.5f,\"freeMargin\":%.4f,\"serverMarginPerLot\":%.4f}",
    name.c_str(),modeOf(plan),plan.pct,d.capacity,d.finalVolume,tried.c_str(),caps.c_str(),filledVol,
    attempts,b(gaveUp).c_str(),modeOf(after),after.pct,ServerCapacityCeiling(),BRK.freeMargin,
    BRK.serverMarginPerLot));
}

static void emitPlanTable(const std::string &name,const char *profile){
  std::string modes, pcts;
  for(int f=0;f<=7;f++){
    LayerSizingPlan p=PlanLayerSizing(profile,f);
    modes+=(f?",":"")+StringFormat("\"%s\"",p.mode.c_str());
    pcts+=(f?",":"")+StringFormat("%.4f",p.pct);
  }
  row(StringFormat("{\"test\":\"%s\",\"profile\":\"%s\",\"modes\":[%s],\"pcts\":[%s]}",
                   name.c_str(),profile,modes.c_str(),pcts.c_str()));
}

static void resetV388(const char *profile){
  resetBroker();
  C.accountProfile=profile;
  BRK.positions.clear(); BRK.orders.clear();
  layers=0;
}

static void runV388Scenarios(){
  // ---- the state machine itself ---------------------------------------------
  resetV388("UNLIMITED"); emitPlanTable("plan_unlimited","UNLIMITED");
  resetV388("NORMAL");    emitPlanTable("plan_normal","NORMAL");
  resetV388("NORMAL");    emitPlanTable("plan_unknown_profile_takes_safe_ladder","FOO");
  resetV388("NORMAL");    emitLadder("ladder_normal","NORMAL");

  // ---- CRITICAL $1,000 REGRESSION + TESTS 1-4 on the Exness client model --------
  // Client margin model: gold is margin-free, so OrderCalcMargin and OrderCheck both
  // approve SYMBOL_VOLUME_MAX. The OLD unlimited capacity is therefore 200 lots and
  // 15% of it is the 30-lot bug.
  resetV388("UNLIMITED");
  BRK.leverage=2000000000L; BRK.volMax=200.0; BRK.balance=1000.0;
  markTo(4400.0,0);
  emitLayer("unl1000_L1",0,1);
  emitLayer("unl1000_L1_sell",0,-1);
  BRK.volMax=500.0;                       // unlimited capacity 200 -> 500 ...
  emitLayer("unl1000_L1_volmax500",0,1);  // ... L1 must not move
  BRK.volMax=200.0;
  fillPos(0,0.06,4400.0); markTo(4410.0,0);
  emitLayer("unl1000_L2",1,1);
  fillPos(0,0.21,4410.0); markTo(4420.0,0);
  emitLayer("unl1000_L3",2,1);

  // ---- TESTS 3-7 on a money-bound broker (real margin 1:2000) -------------------
  resetV388("UNLIMITED");
  BRK.leverage=2000L; BRK.volMax=200.0; BRK.balance=1000.0;
  markTo(4400.0,2000);
  emitLayer("sane_L1",0,1);
  fillPos(0,0.06,4400.0); markTo(4410.0,2000);
  emitLayer("sane_L2",1,1);
  fillPos(0,0.21,4410.0); markTo(4420.0,2000);
  emitLayer("sane_L3",2,1);
  fillPos(0,5.74,4420.0); markTo(4420.0,2000);
  emitLayer("sane_L4_wait",3,1);          // 100% was used by L3: capacity 0 -> WAIT
  markTo(4425.0,2000);                    // floating profit creates NEW capacity
  emitLayer("sane_L4_after_profit",3,1);
  fillPos(0,13.58,4425.0); markTo(4425.0,2000);
  emitLayer("sane_L5_wait",4,1);
  markTo(4432.0,2000);
  emitLayer("sane_L5_after_profit",4,1);
  fillPos(0,22.63,4432.0); markTo(4440.0,2000);
  emitLayer("sane_L6_after_profit",5,1);

  // ---- TEST 8: L1 artificially rejected ------------------------------------------
  resetV388("UNLIMITED");
  BRK.leverage=2000L; BRK.volMax=200.0; BRK.balance=20000.0;
  markTo(4400.0,2000);
  g_rejectAbove=1.00;
  emitRetry("retry_L1_rejected",0,1);
  g_rejectAbove=0;

  // ---- TEST 9: L2 artificially rejected ------------------------------------------
  resetV388("UNLIMITED");
  BRK.leverage=2000L; BRK.volMax=200.0; BRK.balance=20000.0;
  fillPos(0,1.36,4400.0); markTo(4400.0,2000);
  g_rejectAbove=2.00;
  emitRetry("retry_L2_rejected",1,1);
  g_rejectAbove=0;

  // ---- L3 (100%) retry must still converge on a lying preflight -----------------
  resetV388("UNLIMITED");
  BRK.leverage=2000000000L; BRK.volMax=200.0; BRK.balance=2500.0;
  fillPos(0,0.06,4400.0); fillPos(0,0.21,4400.0); markTo(4400.0,0);
  BRK.serverMarginPerLot=100.0;           // the SERVER charges 100/lot: true capacity 25
  emitRetry("retry_L3_pct100_converges",2,1);

  // ---- server evidence persists into the NEXT campaign's L3 ---------------------
  resetV388("UNLIMITED");
  BRK.leverage=2000000000L; BRK.volMax=200.0; BRK.balance=2500.0; markTo(4400.0,0);
  emitLayer("evidence_cold_L3",2,1);
  g_serverRejectedVolume=30.0; g_serverEvidenceFreeMargin=2500.0; g_serverFilledVolume=0;
  emitLayer("evidence_warm_L3",2,1);
  emitLayer("evidence_warm_L1",0,1);      // evidence 29.99 >> 1:200 capacity: no effect

  // ---- 1:200 margin model coverage ---------------------------------------------
  // FOREX calc mode with a broker initial margin rate of 1.5.
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=10000.0; markTo(4400.0,0);
  BRK.calcMode=SYMBOL_CALC_MODE_FOREX; BRK.marginRateInit=1.5;
  emitLayer("calc_forex_rate_1_5",0,1);
  // CFD calc mode: the broker rate (0.005) already embeds broker leverage -> ignored.
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=10000.0; markTo(4400.0,0);
  BRK.calcMode=SYMBOL_CALC_MODE_CFD; BRK.marginRateInit=0.005;
  emitLayer("calc_cfd_rate_ignored",0,1);
  // Account currency != profit currency: the tick-value conversion is used.
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=10000.0; markTo(4400.0,0);
  BRK.accountCurrency="EUR"; BRK.tickValue=0.085;   // 1 USD = 0.85 EUR
  emitLayer("eur_account_tick_value",0,1);
  // A broker STRICTER than 1:200 (real 1:100): a 1:200 account cannot beat it.
  resetV388("UNLIMITED"); BRK.leverage=100L; BRK.balance=10000.0; markTo(4400.0,100);
  emitLayer("broker_stricter_than_200",0,1);
  // No notional at all (currency mismatch AND no tick value): refuse, never guess.
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=10000.0; markTo(4400.0,0);
  BRK.accountCurrency="EUR"; BRK.tickValue=0.0;
  emitLayer("sim_margin_unavailable_blocks",0,1);

  // ---- SYMBOL_VOLUME_LIMIT (aggregate one-direction exposure) --------------------
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=10000.0;
  BRK.volLimit=5.0;
  fillPos(0,0.50,4400.0); fillPos(0,4.20,4400.0);
  BRK.orders.push_back(MockOrder{"XAUUSDm",ORDER_TYPE_BUY_LIMIT,0.10});
  markTo(4400.0,0);
  emitLayer("volume_limit_L3",2,1);       // room = 5.0 - 4.7 - 0.1 = 0.2
  BRK.volLimit=4.8;
  emitLayer("volume_limit_reached_L3",2,1);
  // The 1:200 engine honours the same broker rule: L1 0.06 open + 0.10 pending buy
  // against a 0.50 limit leaves 0.34 lots of room, far below the 4.48-lot 1:200 capacity.
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=10000.0;
  BRK.volLimit=0.50;
  fillPos(0,0.06,4400.0);
  BRK.orders.push_back(MockOrder{"XAUUSDm",ORDER_TYPE_BUY_LIMIT,0.10});
  BRK.orders.push_back(MockOrder{"XAUUSDm",ORDER_TYPE_SELL_LIMIT,5.00});   // other side: ignored
  markTo(4400.0,0);
  emitLayer("volume_limit_L2",1,1);

  // ---- tiny account: a 1:200 account cannot open 0.01 lot at 15% -----------------
  resetV388("UNLIMITED"); BRK.leverage=200000000L; BRK.balance=20.40; markTo(4400.0,0);
  emitLayer("unl20_L1",0,1);
  resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=150.0; markTo(4400.0,0);
  emitLayer("unl150_L1_min_lot",0,1);

  // ---- volume steps never round UP past the 15% budget --------------------------
  for(double st : {0.01,0.1,0.25}){
    resetV388("UNLIMITED"); BRK.leverage=2000000000L; BRK.balance=25000.0; markTo(4400.0,0);
    BRK.volStep=st; BRK.volMin=st;
    emitLayer(StringFormat("sim_step_%.2f",st),0,1);
  }

  // ---- TEST 10: NORMAL is unchanged -------------------------------------------------
  // Every NORMAL scenario sized through the NEW entry point must equal the untouched
  // ComputeVolume() exactly, field by field.
  struct NCase { const char *name; double mpl, free, ask, bid; long lev, ref; int dir; int filled; };
  NCase cases[]={
    {"normal_incident_L1",0.0,1000.0,4421.664,4421.564,2000000000L,500,-1,0},
    {"normal_incident_L2",0.0,3318.99,4421.664,4421.564,2000000000L,500,-1,1},
    {"normal_1200_L3",0.0,1200.0,4421.664,4421.564,2000000000L,500,-1,2},
    {"normal_1200_L4",0.0,800.0,4421.664,4421.564,2000000000L,500,-1,3},
    {"normal_linear_L1",880.2,10000.0,4401.10,4401.0,500L,0,1,0},
    {"normal_linear_L2",880.2,10000.0,4401.10,4401.0,500L,0,1,1},
    {"normal_linear_L3",880.2,10000.0,4401.10,4401.0,500L,0,1,2},
    {"normal_auto_pathological_blocks",0.0,1000.0,4421.664,4421.564,2000000000L,0,-1,0}
  };
  for(auto &c:cases){
    resetV388("NORMAL");
    BRK.marginPerLot=c.mpl; BRK.freeMargin=c.free; BRK.ask=c.ask; BRK.bid=c.bid;
    BRK.leverage=c.lev; C.normalReferenceLeverage=c.ref; layers=c.filled;
    double price=c.dir>0?BRK.ask:BRK.bid;
    LayerSizingPlan plan=PlanLayerSizing(ExecutionProfile(),c.filled);
    SizingDecision viaPlan=ComputeLayerVolume(plan,c.dir,price,0);
    SizingDecision direct=ComputeVolume(c.dir,LayerMarginPct(),price,0);
    bool same=viaPlan.finalVolume==direct.finalVolume&&viaPlan.capacity==direct.capacity&&
              viaPlan.blockReason==direct.blockReason&&viaPlan.capacitySource==direct.capacitySource&&
              viaPlan.sizingModel==direct.sizingModel&&viaPlan.budget==direct.budget&&
              viaPlan.moneyCapacity==direct.moneyCapacity&&viaPlan.checkRetcode==direct.checkRetcode;
    row(StringFormat("{\"test\":\"%s\",\"mode\":\"%s\",\"pct\":%.4f,\"final\":%.5f,\"directFinal\":%.5f,"
                     "\"capacity\":%.5f,\"capacitySource\":\"%s\",\"block\":\"%s\",\"identical\":%s,"
                     "\"simulatedLeverage\":%lld}",
                     c.name,plan.mode.c_str(),plan.pct,viaPlan.finalVolume,direct.finalVolume,
                     viaPlan.capacity,viaPlan.capacitySource.c_str(),viaPlan.blockReason.c_str(),
                     b(same).c_str(),viaPlan.simulatedLeverage));
  }
}

int main(){
  // ---------- A: the live Exness incident ----------------------------------
  // Client-side margin model reports ZERO margin for gold (Exness unlimited-leverage
  // style). v3.7.1's SYMBOL_VOLUME_MAX shortcut then returns 200.00 lots for a NORMAL
  // L1 "15% probe". Reproduces the 2026-09-07 01:39 / 05:27 / 06:34 rejections.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  emitSizing("live_exness_zero_margin_normal_L1",1,15.0,BRK.ask,BRK.ask-30.0);
  emitSizing("live_exness_zero_margin_normal_L2",1,50.0,BRK.ask,0);
  emitSizing("live_exness_zero_margin_normal_L3",1,100.0,BRK.ask,0);

  // ---------- B: EXACT replay of the 2026-09-08 01:24 demo 476885386 incident ----
  // Verbatim from the terminal's own telemetry:
  //   APEX SIZING | profile=NORMAL layer=L1 pct=15.00 | leverage=1:2000000000
  //   freeMargin=1000.00 | volMax=200.0000 | marginAt1Lot=0.00
  //   capacityByMargin=200.0000 | byCapacityPct=30.0000 | FINAL=30.0000
  // and the broker Journal: "market sell 30 XAUUSDm", then L2 "market sell 100".
  // The broker margin model is pathological, so NORMAL must fall back to the OWNER
  // CONFIGURED reference leverage (1:500 for this account), never to SYMBOL_VOLUME_MAX.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664;
  C.normalReferenceLeverage=500;
  emitSizing("incident_476885386_L1_15pct",-1,15.0,BRK.bid,4451.738);
  BRK.freeMargin=3318.99;
  emitSizing("incident_476885386_L2_50pct",-1,50.0,BRK.bid,0);

  // Same pathological broker, but AUTO (no configured reference leverage): refuse.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664;
  emitSizing("pathological_auto_without_reference_blocks",-1,15.0,BRK.bid,0);

  // ---------- the $1,200 account the owner intends to run next ---------------
  // NORMAL, reference leverage 1:500, gold ~4421.564, 100oz contract.
  // margin/lot = 100*4421.564/500 = 884.31 -> capacity 1.35 lots.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664;
  C.normalReferenceLeverage=500;
  emitSizing("acct1200_ref500_L1",-1,15.0,BRK.bid,0);
  emitSizing("acct1200_ref500_L2",-1,50.0,BRK.bid,0);
  emitSizing("acct1200_ref500_L3",-1,100.0,BRK.bid,0);

  // ---------- reference leverage matrix: 1:100 / 1:200 / 1:500 --------------
  // Same $1,200 and price; only the configured economic leverage differs, so the
  // capacity (and therefore every tier) must scale linearly with it.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=100;
  emitSizing("ref_lev_100_L1",-1,15.0,BRK.bid,0);
  emitSizing("ref_lev_100_L3",-1,100.0,BRK.bid,0);
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=200;
  emitSizing("ref_lev_200_L1",-1,15.0,BRK.bid,0);
  emitSizing("ref_lev_200_L3",-1,100.0,BRK.bid,0);
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=500;
  emitSizing("ref_lev_500_L1",-1,15.0,BRK.bid,0);
  emitSizing("ref_lev_500_L3",-1,100.0,BRK.bid,0);

  // ---------- L4+ must keep adding at 100% of CURRENT capacity -------------
  // Free margin falls as layers open; each add re-reads it. L3, L4 and L5 are all
  // 100% tiers, so each must equal 100% of the capacity available AT THAT MOMENT --
  // decreasing, but never blocked merely for being past L3.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.leverage=2000000000L;
  BRK.bid=4421.564; BRK.ask=4421.664; C.normalReferenceLeverage=500;
  BRK.freeMargin=1200.0; emitSizing("layer_ladder_L3_100pct",-1,100.0,BRK.bid,0);
  BRK.freeMargin=800.0;  emitSizing("layer_ladder_L4_100pct",-1,100.0,BRK.bid,0);
  BRK.freeMargin=400.0;  emitSizing("layer_ladder_L5_100pct",-1,100.0,BRK.bid,0);

  // The $20 UNLIMITED live account's reported 1:200000000 leverage, NORMAL profile
  // with no configured reference leverage: refuse rather than guess.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=20.40; BRK.leverage=200000000L;
  emitSizing("degenerate_leverage_normal_refuses",1,15.0,BRK.ask,0);

  // A lowercase profile must NOT fall through to the aggressive path.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  C.accountProfile="normal";
  emitSizing("lowercase_profile_still_normal",1,15.0,BRK.ask,0);

  // A NORMAL account on a SANE broker must ignore the reference leverage entirely.
  resetBroker();
  BRK.marginPerLot=880.2; BRK.freeMargin=10000.0; BRK.volMax=200.0; BRK.leverage=500;
  C.normalReferenceLeverage=100;   // configured, but must NOT be used
  emitSizing("sane_broker_ignores_reference_leverage",1,15.0,BRK.ask,0);

  // ---------- C: UNLIMITED profile must stay aggressive ---------------------
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  C.accountProfile="UNLIMITED";
  emitSizing("unlimited_profile_full_allocation",1,100.0,BRK.ask,0);

  // UNLIMITED on the same degenerate $20 account stays aggressive -- the capacity
  // gate is NORMAL-only and must not quietly neuter the owner's chosen profile.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=20.40; BRK.leverage=200000000L;
  C.accountProfile="UNLIMITED";
  emitSizing("unlimited_degenerate_leverage_stays_aggressive",1,100.0,BRK.ask,0);

  // ---------- ordinary linear-margin account: behaviour must be UNCHANGED ---
  resetBroker();
  BRK.marginPerLot=880.2;   // 1:500, 100oz contract, gold 4401
  BRK.freeMargin=10000.0; BRK.volMax=200.0;
  emitSizing("linear_margin_1to500_L1_unchanged",1,15.0,BRK.ask,0);
  emitSizing("linear_margin_1to500_L2_unchanged",1,50.0,BRK.ask,0);
  emitSizing("linear_margin_1to500_L3_unchanged",1,100.0,BRK.ask,0);

  // ---------- APEX-AUDIT-009: minimum lot must not exceed the budget --------
  resetBroker();
  BRK.volMin=0.1; BRK.volStep=0.1; BRK.marginPerLot=100.0; BRK.freeMargin=10.0; BRK.volMax=200.0;
  emitSizing("min_lot_margin_exceeds_budget",1,15.0,BRK.ask,0);

  // ---------- non-decimal / quarter volume steps ---------------------------
  resetBroker();
  BRK.volMin=0.25; BRK.volStep=0.25; BRK.marginPerLot=100.0; BRK.freeMargin=1000.0; BRK.volMax=50.0;
  emitSizing("quarter_volume_step",1,100.0,BRK.ask,0);
  row(StringFormat("{\"test\":\"vol_digits_quarter_step\",\"v380Digits\":%d,\"v371Digits\":%d}",
                   VolDigits(),v371_VolDigits()));
  resetBroker();
  BRK.volMin=0.00125; BRK.volStep=0.00125; BRK.marginPerLot=100.0; BRK.freeMargin=1000.0; BRK.volMax=50.0;
  emitSizing("nondecimal_volume_step",1,100.0,BRK.ask,0);
  row(StringFormat("{\"test\":\"vol_digits_nondecimal_step\",\"v380Digits\":%d,\"v371Digits\":%d}",
                   VolDigits(),v371_VolDigits()));

  // ---------- owner exposure controls are OFF by default -------------------
  resetBroker();
  BRK.marginPerLot=880.2; BRK.freeMargin=10000.0;
  double withoutCaps=ComputeVolume(1,100.0,BRK.ask,0).finalVolume;
  C.maxBasketLots=2.0;
  double withCap=ComputeVolume(1,100.0,BRK.ask,0).finalVolume;
  row(StringFormat("{\"test\":\"owner_caps_opt_in\",\"defaultVolume\":%.5f,\"cappedVolume\":%.5f}",
                   withoutCaps,withCap));

  // ---------- B: broker rejects the size the client model approved ---------
  // The terminal's margin model reports zero margin for gold, so OrderCalcMargin AND
  // OrderCheck both approve. The SERVER still charges 880.2/lot, so only the real
  // submission fails -- exactly the "[No money]" shape seen on the demo account.
  resetBroker();
  BRK.marginPerLot=0.0;            // client model: gold is margin-free
  BRK.serverMarginPerLot=880.2;    // broker truth: 1:500 on a 100oz contract at 4401
  BRK.volMax=200.0; BRK.freeMargin=1000.0;
  {
    SizingDecision d371;
    double v371=v371_VolumeForMargin(1,15.0);
    SizingDecision d=ComputeVolume(1,15.0,BRK.ask,0);
    DescentResult old=descend(1,v371);
    DescentResult neu=descend(1,d.finalVolume);
    std::string tried;
    for(size_t i=0;i<neu.tried.size();i++) tried+=(i?",":"")+StringFormat("%.5f",neu.tried[i]);
    row(StringFormat("{\"test\":\"broker_rejects_client_approved_size\",\"v371Volume\":%.5f,"
                     "\"v380InitialVolume\":%.5f,\"attempts\":%d,\"tried\":[%s],"
                     "\"filledVolume\":%.5f,\"gaveUp\":%s,\"serverAffordable\":%.5f,"
                     "\"v371AttemptsToFill\":%d,\"v371Filled\":%.5f}",
                     v371,d.finalVolume,neu.attempts,tried.c_str(),neu.filled,
                     b(neu.gaveUp).c_str(),BRK.freeMargin/880.2,old.attempts,old.filled));
  }

  // ---------- APEX-AUDIT-001: final executable-price eligibility ------------
  // Same closed bars, three different live quotes. Sell setup: swept high 4410,
  // structural trigger close 4400, ATR 2.0.
  resetBroker();
  BRK.lastClosedM1=1000000;
  BRK.now=1000030;
  BRK.bid=4399.0; BRK.ask=4399.1;
  emitGate("gate_in_zone_quote",-1,4410.0,4400.0,2.0,1000000);
  BRK.bid=4411.0; BRK.ask=4411.1;             // price reclaimed the rejected high
  emitGate("gate_reclaimed_extreme",-1,4410.0,4400.0,2.0,1000000);
  BRK.bid=4390.0; BRK.ask=4390.1;             // 5 ATR beyond the trigger = chasing
  emitGate("gate_extended_chase_shadow",-1,4410.0,4400.0,2.0,1000000);
  InpEntryExtensionMode=GATE_ENFORCE;
  emitGate("gate_extended_chase_enforced",-1,4410.0,4400.0,2.0,1000000);
  InpEntryExtensionMode=GATE_SHADOW;
  BRK.bid=4399.0; BRK.ask=4399.1;
  BRK.lastClosedM1=1000060;                    // a newer bar has closed since the trigger
  emitGate("gate_stale_trigger_bar",-1,4410.0,4400.0,2.0,1000000);
  BRK.lastClosedM1=1000000;
  InpMaxQuoteAgeMs=1500;
  BRK.quoteMsc=(long)(BRK.now-10)*1000;        // 10s-old tick
  emitGate("gate_stale_quote",-1,4410.0,4400.0,2.0,1000000);
  BRK.quoteMsc=0; InpMaxQuoteAgeMs=0;
  InpRejectReclaimedExtreme=false;
  BRK.bid=4411.0; BRK.ask=4411.1;
  emitGate("gate_reclaim_check_disabled",-1,4410.0,4400.0,2.0,1000000);

  // Reclaim of campaign invalidation still blocks (v3.8.2 gate, not origin-box)
  resetBroker();
  BRK.lastClosedM1=1000000; BRK.now=1000030;
  BRK.bid=4411.0; BRK.ask=4411.1;
  emitGate("gate_add_blocked_after_invalidation_reclaim",-1,4410.0,4385.0,2.0,1000000);

  // v3.8.6: WAF HTML 403 is transport; authenticated XauCloud JSON envelope is denial
  resetBroker();
  {
    bool html=BodyLooksLikeJsonObject("<html>cloudflare 403</html>");
    bool empty=BodyLooksLikeJsonObject("   ");
    bool json=BodyLooksLikeJsonObject(" {\"ok\":false}");
    bool waf=IsXauCloudDenialEnvelope(true,"","","",false,true);
    bool denied=IsXauCloudDenialEnvelope(true,"LICENSE_DENIED","","",true,false);
    bool expired=IsXauCloudDenialEnvelope(true,"EXPIRED","","LICENSE_EXPIRED",true,false);
    bool active=IsXauCloudDenialEnvelope(true,"ACTIVE","","",true,true);
    row(StringFormat("{\"test\":\"waf_vs_license_envelope\",\"htmlIsJson\":%s,\"emptyIsJson\":%s,\"jsonObj\":%s,"
                     "\"wafDenied\":%s,\"licenseDenied\":%s,\"expiredDenied\":%s,\"activeDenied\":%s}",
                     b(html).c_str(),b(empty).c_str(),b(json).c_str(),
                     b(waf).c_str(),b(denied).c_str(),b(expired).c_str(),b(active).c_str()));
  }

  // v3.8.5: PLACED is pending (2), fill is 1, other is reject (0)
  resetBroker();
  {
    int filled=ClassifyBrokerSubmit(TRADE_RETCODE_DONE,true);
    int placed=ClassifyBrokerSubmit(TRADE_RETCODE_PLACED,false);
    int placedButFilled=ClassifyBrokerSubmit(TRADE_RETCODE_PLACED,true);
    int nomoney=ClassifyBrokerSubmit(TRADE_RETCODE_NO_MONEY,false);
    row(StringFormat("{\"test\":\"placed_is_pending_not_reject\",\"filled\":%d,\"placed\":%d,\"placedButFilled\":%d,\"nomoney\":%d}",
                     filled,placed,placedButFilled,nomoney));
  }

  // v3.8.5: cross-terminal lease fencing. Network loss never opens a second manager.
  resetBroker();
  {
    datetime now=1'700'000'000;
    bool noCloud=ManagerAllowsNewExposure("A","",(datetime)0,now,false,false);
    bool weHold=ManagerAllowsNewExposure("A","A",now+30,now,true,true);
    bool otherHolds=ManagerAllowsNewExposure("B","A",now+30,now,true,false);
    bool expiredWeWere=ManagerAllowsNewExposure("A","A",now-1,now,true,true);
    bool partitionEmpty=ManagerAllowsNewExposure("A","",now+30,now,true,false);
    bool partitionWeWere=ManagerAllowsNewExposure("A","",now+30,now,true,true);
    row(StringFormat("{\"test\":\"cross_terminal_lease\",\"noCloudAllows\":%s,\"weHold\":%s,\"otherHolds\":%s,"
                     "\"expiredBlocked\":%s,\"partitionWithoutPriorBlocked\":%s,\"partitionWithPriorUntilOk\":%s}",
                     b(noCloud).c_str(),b(weHold).c_str(),b(otherHolds).c_str(),
                     b(!expiredWeWere).c_str(),b(!partitionEmpty).c_str(),b(partitionWeWere).c_str()));
  }

  // v3.8.5: restart-while-confirmed snapshot restore; expired / reclaimed refused
  resetBroker();
  {
    datetime now=1'700'000'000;
    bool watching=SetupSnapshotValidToRestore(SETUP_WATCHING,-1,0,now-60,now,12,4410.0,false);
    bool confirmed=SetupSnapshotValidToRestore(SETUP_CONFIRMED,-1,now-30,now-600,now,12,4410.0,false);
    bool expiredWatch=SetupSnapshotValidToRestore(SETUP_WATCHING,-1,0,now-13*60,now,12,4410.0,false);
    bool expiredFromArmedNotConfirm=SetupSnapshotValidToRestore(SETUP_CONFIRMED,-1,now-30,now-13*60,now,12,4410.0,false);
    bool reclaimed=SetupSnapshotValidToRestore(SETUP_CONFIRMED,-1,now-30,now-60,now,12,4410.0,true);
    bool idle=SetupSnapshotValidToRestore(SETUP_NONE,-1,now-30,now-60,now,12,4410.0,false);
    row(StringFormat("{\"test\":\"restart_while_confirmed\",\"watchingOk\":%s,\"confirmedOk\":%s,"
                     "\"expiredWatchBlocked\":%s,\"confirmedUsesConfirmedAt\":%s,\"reclaimedBlocked\":%s,\"idleBlocked\":%s}",
                     b(watching).c_str(),b(confirmed).c_str(),
                     b(!expiredWatch).c_str(),b(expiredFromArmedNotConfirm).c_str(),
                     b(!reclaimed).c_str(),b(!idle).c_str()));
  }

  runV388Scenarios();
  return 0;
}
