// Scenario driver. The Apex logic under test is #included verbatim from the real .mq5
// sources (generated by tests/native/extract.mjs into extracted.h). Emits one JSON
// object per scenario on stdout.
#include "mt5shim.h"
MockBroker  BRK;
ApexConfig  C;
long        InpMagic=8620260903L;
int         InpMaxQuoteAgeMs=0;
bool        InpRequireFreshTrigger=true;
bool        InpRejectReclaimedExtreme=true;
double      InpMaxEntryExtensionAtr=1.50;
ApexGateMode InpEntryExtensionMode=GATE_SHADOW;
#include "extracted.h"

#include <iostream>
static void row(const std::string &s){ std::cout<<s<<"\n"; }
static std::string b(bool v){ return v?"true":"false"; }

static void resetBroker(){
  BRK=MockBroker();
  C=ApexConfig();
  InpMaxQuoteAgeMs=0; InpRequireFreshTrigger=true; InpRejectReclaimedExtreme=true;
  InpMaxEntryExtensionAtr=1.50; InpEntryExtensionMode=GATE_SHADOW;
}

// Mirrors the retry loop in OpenLayer (halve onto the grid while the rejection is
// size-only). tests/ea_static.test.mjs asserts the real OpenLayer contains this loop.
struct DescentResult { double filled; int attempts; std::vector<double> tried; bool gaveUp; };
static DescentResult descend(int dir,double start){
  DescentResult r; r.filled=0; r.attempts=0; r.gaveUp=false;
  double vol=start;
  for(int i=0;i<10;i++){
    r.tried.push_back(vol); r.attempts++;
    double need=BRK.serverMargin(vol);
    if(need<=BRK.freeMargin+1e-9){ r.filled=vol; return r; }
    uint rc=TRADE_RETCODE_NO_MONEY;
    if(!IsSizeOnlyRejection(rc,0)) break;
    double next=FloorToStep(vol*0.5);
    if(next<BRK.volMin||next<=0){ r.gaveUp=true; return r; }
    vol=next;
  }
  r.gaveUp=true; return r;
}

static void emitSizing(const std::string &name,int dir,double pct,double price,double sl){
  double v371=v371_VolumeForMargin(dir,pct);
  SizingDecision d=ComputeVolume(dir,pct,price,sl);
  row(StringFormat(
    "{\"test\":\"%s\",\"pct\":%.2f,\"volMin\":%.5f,\"volMax\":%.5f,\"volStep\":%.5f,"
    "\"freeMargin\":%.2f,\"marginPerLot\":%.4f,\"v371Volume\":%.5f,\"v380Volume\":%.5f,"
    "\"capacityByMargin\":%.5f,\"capacityByBroker\":%.5f,\"byCapacityPct\":%.5f,"
    "\"byMarginBudget\":%.5f,\"budget\":%.2f,\"block\":\"%s\",\"orderCheckRetcode\":%u}",
    name.c_str(),pct,d.volMin,d.volMax,d.volStep,d.freeMargin,BRK.marginPerLot,
    v371,d.finalVolume,d.capacityByMargin,d.capacityByBroker,d.byCapacityPct,
    d.byMarginBudget,d.budget,d.blockReason.c_str(),d.checkRetcode));
}

static void emitGate(const std::string &name,int dir,double invalidLevel,double refPrice,
                     double atr,datetime triggerBar){
  Gate g;
  bool ok=FinalEntryGate(dir,invalidLevel,refPrice,atr,triggerBar,true,g);
  row(StringFormat(
    "{\"test\":\"%s\",\"ok\":%s,\"reason\":\"%s\",\"bid\":%.5f,\"ask\":%.5f,"
    "\"extensionAtr\":%.4f,\"reclaimed\":%s,\"triggerStale\":%s,\"quoteStale\":%s,\"extended\":%s}",
    name.c_str(),b(ok).c_str(),g.reason.c_str(),g.bid,g.ask,g.extensionAtr,
    b(g.reclaimed).c_str(),b(g.triggerStale).c_str(),b(g.quoteStale).c_str(),b(g.extended).c_str()));
}

int main(){
  // ---------- A: the live Exness incident ----------------------------------
  // Client-side margin model reports ZERO margin for gold (Exness unlimited-leverage
  // style). v3.7.1's SYMBOL_VOLUME_MAX shortcut then returns 200.00 lots for a NORMAL
  // L1 "15% probe". Reproduces the 2026-09-07 01:39 / 05:27 / 06:34 rejections.
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  emitSizing("live_exness_zero_margin_normal_L1",1,15.0,BRK.ask,BRK.ask-30.0);
  emitSizing("live_exness_zero_margin_normal_L2",1,50.0,BRK.ask,0);
  emitSizing("live_exness_zero_margin_normal_L3",1,100.0,BRK.ask,0);

  // ---------- C: UNLIMITED profile must stay aggressive ---------------------
  resetBroker();
  BRK.marginPerLot=0.0; BRK.volMax=200.0; BRK.freeMargin=1000.0;
  C.accountProfile="UNLIMITED";
  emitSizing("unlimited_profile_full_allocation",1,100.0,BRK.ask,0);

  // ---------- ordinary linear-margin account: behaviour must be UNCHANGED ---
  resetBroker();
  BRK.marginPerLot=880.2;   // 1:500, 100oz contract, gold 4401
  BRK.freeMargin=10000.0; BRK.volMax=200.0;
  emitSizing("linear_margin_1to500_L1_unchanged",1,15.0,BRK.ask,0);
  emitSizing("linear_margin_1to500_L2_unchanged",1,50.0,BRK.ask,0);
  emitSizing("linear_margin_1to500_L3_unchanged",1,100.0,BRK.ask,0);

  // ---------- APEX-AUDIT-009: minimum lot must not exceed the budget --------
  resetBroker();
  BRK.volMin=0.1; BRK.volStep=0.1; BRK.marginPerLot=100.0; BRK.freeMargin=10.0; BRK.volMax=200.0;
  emitSizing("min_lot_margin_exceeds_budget",1,15.0,BRK.ask,0);

  // ---------- non-decimal / quarter volume steps ---------------------------
  resetBroker();
  BRK.volMin=0.25; BRK.volStep=0.25; BRK.marginPerLot=100.0; BRK.freeMargin=1000.0; BRK.volMax=50.0;
  emitSizing("quarter_volume_step",1,100.0,BRK.ask,0);
  row(StringFormat("{\"test\":\"vol_digits_quarter_step\",\"v380Digits\":%d,\"v371Digits\":%d}",
                   VolDigits(),v371_VolDigits()));
  resetBroker();
  BRK.volMin=0.00125; BRK.volStep=0.00125; BRK.marginPerLot=100.0; BRK.freeMargin=1000.0; BRK.volMax=50.0;
  emitSizing("nondecimal_volume_step",1,100.0,BRK.ask,0);
  row(StringFormat("{\"test\":\"vol_digits_nondecimal_step\",\"v380Digits\":%d,\"v371Digits\":%d}",
                   VolDigits(),v371_VolDigits()));

  // ---------- owner exposure controls are OFF by default -------------------
  resetBroker();
  BRK.marginPerLot=880.2; BRK.freeMargin=10000.0;
  double withoutCaps=ComputeVolume(1,100.0,BRK.ask,0).finalVolume;
  C.maxBasketLots=2.0;
  double withCap=ComputeVolume(1,100.0,BRK.ask,0).finalVolume;
  row(StringFormat("{\"test\":\"owner_caps_opt_in\",\"defaultVolume\":%.5f,\"cappedVolume\":%.5f}",
                   withoutCaps,withCap));

  // ---------- B: broker rejects the size the client model approved ---------
  // The terminal's margin model reports zero margin for gold, so OrderCalcMargin AND
  // OrderCheck both approve. The SERVER still charges 880.2/lot, so only the real
  // submission fails -- exactly the "[No money]" shape seen on the demo account.
  resetBroker();
  BRK.marginPerLot=0.0;            // client model: gold is margin-free
  BRK.serverMarginPerLot=880.2;    // broker truth: 1:500 on a 100oz contract at 4401
  BRK.volMax=200.0; BRK.freeMargin=1000.0;
  {
    SizingDecision d371;
    double v371=v371_VolumeForMargin(1,15.0);
    SizingDecision d=ComputeVolume(1,15.0,BRK.ask,0);
    DescentResult old=descend(1,v371);
    DescentResult neu=descend(1,d.finalVolume);
    std::string tried;
    for(size_t i=0;i<neu.tried.size();i++) tried+=(i?",":"")+StringFormat("%.5f",neu.tried[i]);
    row(StringFormat("{\"test\":\"broker_rejects_client_approved_size\",\"v371Volume\":%.5f,"
                     "\"v380InitialVolume\":%.5f,\"attempts\":%d,\"tried\":[%s],"
                     "\"filledVolume\":%.5f,\"gaveUp\":%s,\"serverAffordable\":%.5f,"
                     "\"v371AttemptsToFill\":%d,\"v371Filled\":%.5f}",
                     v371,d.finalVolume,neu.attempts,tried.c_str(),neu.filled,
                     b(neu.gaveUp).c_str(),BRK.freeMargin/880.2,old.attempts,old.filled));
  }

  // ---------- APEX-AUDIT-001: final executable-price eligibility ------------
  // Same closed bars, three different live quotes. Sell setup: swept high 4410,
  // structural trigger close 4400, ATR 2.0.
  resetBroker();
  BRK.lastClosedM1=1000000;
  BRK.now=1000030;
  BRK.bid=4399.0; BRK.ask=4399.1;
  emitGate("gate_in_zone_quote",-1,4410.0,4400.0,2.0,1000000);
  BRK.bid=4411.0; BRK.ask=4411.1;             // price reclaimed the rejected high
  emitGate("gate_reclaimed_extreme",-1,4410.0,4400.0,2.0,1000000);
  BRK.bid=4390.0; BRK.ask=4390.1;             // 5 ATR beyond the trigger = chasing
  emitGate("gate_extended_chase_shadow",-1,4410.0,4400.0,2.0,1000000);
  InpEntryExtensionMode=GATE_ENFORCE;
  emitGate("gate_extended_chase_enforced",-1,4410.0,4400.0,2.0,1000000);
  InpEntryExtensionMode=GATE_SHADOW;
  BRK.bid=4399.0; BRK.ask=4399.1;
  BRK.lastClosedM1=1000060;                    // a newer bar has closed since the trigger
  emitGate("gate_stale_trigger_bar",-1,4410.0,4400.0,2.0,1000000);
  BRK.lastClosedM1=1000000;
  InpMaxQuoteAgeMs=1500;
  BRK.quoteMsc=(long)(BRK.now-10)*1000;        // 10s-old tick
  emitGate("gate_stale_quote",-1,4410.0,4400.0,2.0,1000000);
  BRK.quoteMsc=0; InpMaxQuoteAgeMs=0;
  InpRejectReclaimedExtreme=false;
  BRK.bid=4411.0; BRK.ask=4411.1;
  emitGate("gate_reclaim_check_disabled",-1,4410.0,4400.0,2.0,1000000);

  return 0;
}
