#property copyright "XauCloud Apex"
#property version   "2.100"
#property strict
#property description "ApexStack: XAUUSD exhaustion/reversal campaign with aggressive profit-side pyramiding"
#include <Trade/Trade.mqh>
CTrade trade;
#define APEX_VERSION "XauCloud-Apex-TraderSync_v2.1.0"
#define APEX_MAGIC 8620260903
input string InpApiBase="https://apex.xaucloud.io";
input string InpEaToken="REPLACE_EA_TOKEN";
input int InpConfigPollSeconds=8;
input int InpScanMilliseconds=250;
input bool InpRequireRemoteArm=true;
input long InpMagic=APEX_MAGIC;
struct Config{bool armed;string account;string symbolContains;string targetMode,accountProfile;double targetEquity,targetMultiplier,normalTargetProfitPct,baseMarginPct,layerMultiplier;int maxLayers;double entryScore,addScore,impulseAtr,sweepAtr,addSpacingAtr,rejectionZoneAtr;int rejectionBars,watchExpiryMinutes,cooldownMinutes;bool requireM3Confirm,requireM5Context,learningEnabled,normalProfitFloorEnabled;double learnEntryAdj,learnAddAdj;};
struct Snap{bool valid;int dir;double score,atr,price,extreme,impulseMult,sweepMult,wickRatio;bool swept,rejected,microBreak,m3,m5,continuation,pullbackFail;string sig,reason;};
Config C;int hAtr=INVALID_HANDLE;datetime lastCfg=0,lastEnd=0;bool camp=false;int campDir=0,layers=0;double cycleStart=0,targetEq=0,lastAdd=0,mfe=0,mae=0,peakProfitPct=0,floorProfitPct=0;datetime campStart=0;string campId="",campSig="";
bool watch=false;int watchDir=0;datetime watchStart=0,watchSweepBarTime=0;double watchExtreme=0,watchPrior=0,watchAtr=0;string watchSig="";
string trim(string s){StringTrimLeft(s);StringTrimRight(s);return s;} string raw(string j,string k){string n="\""+k+"\":";int p=StringFind(j,n);if(p<0)return"";p+=StringLen(n);while(p<StringLen(j)&&StringGetCharacter(j,p)==' ')p++;ushort c=StringGetCharacter(j,p);if(c=='\"'){int e=p+1;while(e<StringLen(j)&&StringGetCharacter(j,e)!='\"')e++;return StringSubstr(j,p+1,e-p-1);}int e=p;while(e<StringLen(j)){ushort x=StringGetCharacter(j,e);if(x==','||x=='}'||x==']')break;e++;}return trim(StringSubstr(j,p,e-p));}
double jd(string j,string k,double d){string v=raw(j,k);return v==""?d:StringToDouble(v);} int ji(string j,string k,int d){string v=raw(j,k);return v==""?d:(int)StringToInteger(v);} bool jb(string j,string k,bool d){string v=raw(j,k);if(v=="true")return true;if(v=="false")return false;return d;} string js(string j,string k,string d){string v=raw(j,k);return v==""?d:v;}
bool Http(string method,string ep,string body,string &resp){if((bool)MQLInfoInteger(MQL_TESTER))return false;string hdr="Authorization: Bearer "+InpEaToken+"\r\nContent-Type: application/json\r\n";char d[],r[];string rh;StringToCharArray(body,d,0,WHOLE_ARRAY,CP_UTF8);ResetLastError();int code=WebRequest(method,InpApiBase+ep,hdr,7000,d,r,rh);if(code<0){Print("APEX_HTTP_ERROR ",GetLastError());return false;}resp=CharArrayToString(r,0,-1,CP_UTF8);return code>=200&&code<300;}
void Emit(string type,string extra=""){string b=StringFormat("{\"type\":\"%s\",\"account\":\"%I64d\",\"symbol\":\"%s\",\"version\":\"%s\",\"campaignId\":\"%s\",\"signature\":\"%s\",\"direction\":%d,\"layers\":%d,\"balance\":%.2f,\"equity\":%.2f,\"freeMargin\":%.2f%s}",type,AccountInfoInteger(ACCOUNT_LOGIN),_Symbol,APEX_VERSION,campId,campSig,campDir,layers,AccountInfoDouble(ACCOUNT_BALANCE),AccountInfoDouble(ACCOUNT_EQUITY),AccountInfoDouble(ACCOUNT_MARGIN_FREE),extra);string r;Http("POST","/api/ea/event",b,r);}
void Defaults(){C.armed=!InpRequireRemoteArm;C.account="0";C.symbolContains="XAUUSD";C.targetMode="MULTIPLIER";C.accountProfile="NORMAL";C.targetEquity=1000;C.targetMultiplier=100;C.normalTargetProfitPct=1000;C.baseMarginPct=15;C.layerMultiplier=2;C.maxLayers=0;C.entryScore=76;C.addScore=70;C.impulseAtr=1.8;C.sweepAtr=.05;C.rejectionBars=5;C.watchExpiryMinutes=12;C.addSpacingAtr=.22;C.rejectionZoneAtr=.12;C.cooldownMinutes=0;C.requireM3Confirm=true;C.requireM5Context=false;C.learningEnabled=true;C.normalProfitFloorEnabled=true;C.learnEntryAdj=0;C.learnAddAdj=0;}
bool ConfigPoll(){string r,ep=StringFormat("/api/ea/config?account=%I64d",AccountInfoInteger(ACCOUNT_LOGIN));if(!Http("GET",ep,"",r))return false;C.armed=jb(r,"armed",C.armed);C.account=js(r,"account",C.account);C.symbolContains=js(r,"symbolContains",C.symbolContains);C.targetMode=js(r,"targetMode",C.targetMode);C.accountProfile=js(r,"accountProfile",C.accountProfile);C.targetEquity=jd(r,"targetEquity",C.targetEquity);C.targetMultiplier=jd(r,"targetMultiplier",C.targetMultiplier);C.normalTargetProfitPct=jd(r,"normalTargetProfitPct",C.normalTargetProfitPct);C.baseMarginPct=jd(r,"baseMarginPct",C.baseMarginPct);C.layerMultiplier=jd(r,"layerMultiplier",C.layerMultiplier);C.maxLayers=ji(r,"maxLayers",C.maxLayers);C.entryScore=jd(r,"entryScore",C.entryScore);C.addScore=jd(r,"addScore",C.addScore);C.impulseAtr=jd(r,"impulseAtr",C.impulseAtr);C.sweepAtr=jd(r,"sweepAtr",C.sweepAtr);C.rejectionBars=ji(r,"rejectionBars",C.rejectionBars);C.watchExpiryMinutes=ji(r,"watchExpiryMinutes",C.watchExpiryMinutes);C.addSpacingAtr=jd(r,"addSpacingAtr",C.addSpacingAtr);C.rejectionZoneAtr=jd(r,"rejectionZoneAtr",C.rejectionZoneAtr);C.cooldownMinutes=ji(r,"cooldownMinutes",C.cooldownMinutes);C.requireM3Confirm=jb(r,"requireM3Confirm",C.requireM3Confirm);C.requireM5Context=jb(r,"requireM5Context",C.requireM5Context);C.learningEnabled=jb(r,"learningEnabled",C.learningEnabled);C.normalProfitFloorEnabled=jb(r,"normalProfitFloorEnabled",C.normalProfitFloorEnabled);C.learnEntryAdj=jd(r,"entryScoreAdjustment",0);C.learnAddAdj=jd(r,"addScoreAdjustment",0);return true;}
double ATR(){double x[];ArraySetAsSeries(x,true);if(CopyBuffer(hAtr,0,0,2,x)<2)return 0;return x[1];} bool Rates(ENUM_TIMEFRAMES tf,int n,MqlRates &r[]){ArraySetAsSeries(r,true);return CopyRates(_Symbol,tf,0,n,r)>=n-2;} double clamp(double x,double a,double b){return MathMax(a,MathMin(b,x));}
Snap Observe(){Snap s;s.valid=false;s.dir=0;s.score=0;s.atr=ATR();s.price=0;s.extreme=0;s.impulseMult=0;s.sweepMult=0;s.wickRatio=0;s.swept=false;s.rejected=false;s.microBreak=false;s.m3=false;s.m5=false;s.continuation=false;s.pullbackFail=false;s.sig="NONE";s.reason="";if(s.atr<=0)return s;MqlRates m1[],m3[],m5[];if(!Rates(PERIOD_M1,90,m1)||!Rates(PERIOD_M3,24,m3)||!Rates(PERIOD_M5,18,m5))return s;
 double move=m1[1].close-m1[8].close;int imp=move>=0?1:-1;s.impulseMult=MathAbs(move)/s.atr;int directional=0;for(int i=1;i<=7;i++)if((imp>0&&m1[i].close>m1[i].open)||(imp<0&&m1[i].close<m1[i].open))directional++;
 double ph=-DBL_MAX,pl=DBL_MAX;for(int i=9;i<80;i++){ph=MathMax(ph,m1[i].high);pl=MathMin(pl,m1[i].low);} if(!watch&&s.impulseMult>=C.impulseAtr&&directional>=5){double ex=imp>0?m1[1].high:m1[1].low;bool swept=imp>0?ex>=ph+C.sweepAtr*s.atr:ex<=pl-C.sweepAtr*s.atr;if(swept){watch=true;watchDir=-imp;watchStart=TimeCurrent();watchSweepBarTime=m1[1].time;watchExtreme=ex;watchPrior=imp>0?ph:pl;watchAtr=s.atr;watchSig=watchDir<0?"SELL_UPSIDE_LIQUIDITY_EXHAUST":"BUY_DOWNSIDE_LIQUIDITY_EXHAUST";Emit("WATCH_ARMED",StringFormat(",\"watchDir\":%d,\"impulseAtr\":%.3f",watchDir,s.impulseMult));}}
 if(!watch)return s;if(TimeCurrent()-watchStart>C.watchExpiryMinutes*60){watch=false;return s;} s.dir=watchDir;s.sig=watchSig;s.extreme=watchExtreme;s.swept=true;s.impulseMult=MathAbs(m1[1].close-m1[8].close)/s.atr;s.price=s.dir>0?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID);
 int rb=MathMax(1,MathMin(C.rejectionBars,8));bool rej=false,bos=false;double bestW=0;for(int i=1;i<=rb;i++){if(m1[i].time<=watchSweepBarTime)continue;double body=MathMax(_Point,MathAbs(m1[i].close-m1[i].open));double up=m1[i].high-MathMax(m1[i].open,m1[i].close),lo=MathMin(m1[i].open,m1[i].close)-m1[i].low;if(s.dir<0){bestW=MathMax(bestW,up/body);if(m1[i].high>=watchExtreme-C.rejectionZoneAtr*s.atr&&m1[i].close<watchPrior)rej=true;}else{bestW=MathMax(bestW,lo/body);if(m1[i].low<=watchExtreme+C.rejectionZoneAtr*s.atr&&m1[i].close>watchPrior)rej=true;}}
 if(m1[1].time>watchSweepBarTime){if(s.dir<0)bos=(m1[1].close<m1[2].low)||(m1[1].low<m1[3].low&&m1[1].close<m1[2].open);else bos=(m1[1].close>m1[2].high)||(m1[1].high>m1[3].high&&m1[1].close>m1[2].open);}s.rejected=rej;s.microBreak=bos;s.wickRatio=bestW;s.m3=s.dir<0?(m3[1].close<m3[1].open&&m3[1].close<(m3[1].high+m3[1].low)/2):(m3[1].close>m3[1].open&&m3[1].close>(m3[1].high+m3[1].low)/2);s.m5=s.dir<0?m5[1].close<m5[1].open:m5[1].close>m5[1].open;
 double score=25+clamp(s.impulseMult/C.impulseAtr*15,0,18)+(s.rejected?24:0)+(s.microBreak?22:0)+(s.m3?8:0)+(s.m5?3:0)+clamp(bestW*2,0,5);s.score=clamp(score,0,100);double threshold=C.entryScore+(C.learningEnabled?C.learnEntryAdj:0);s.valid=s.rejected&&s.microBreak&&(!C.requireM3Confirm||s.m3)&&(!C.requireM5Context||s.m5)&&s.score>=threshold;s.reason=s.valid?"CONFIRMED_EXHAUSTION_REVERSAL":"WATCHING_FOR_REJECTION_AND_BOS";return s;}
int VolDigits(){double st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);return st>=1?0:st>=.1?1:st>=.01?2:3;} double NormVol(double v){double mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),mx=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),st=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_STEP);if(st<=0)st=mn;v=MathFloor(v/st)*st;return NormalizeDouble(MathMax(mn,MathMin(mx,v)),VolDigits());}
double VolumeForMargin(int dir,double pct){double free=AccountInfoDouble(ACCOUNT_MARGIN_FREE),budget=free*clamp(pct,.1,100)/100.0,mx=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MAX),mn=SymbolInfoDouble(_Symbol,SYMBOL_VOLUME_MIN),p=dir>0?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID),m=0;ENUM_ORDER_TYPE t=dir>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;if(free<=0)return 0;if(OrderCalcMargin(t,_Symbol,mx,p,m)&&m<=budget)return NormVol(mx);double lo=0,hi=mx;for(int i=0;i<36;i++){double mid=(lo+hi)/2;if(!OrderCalcMargin(t,_Symbol,mid,p,m)||m>budget)hi=mid;else lo=mid;}double v=NormVol(lo);if(v<mn){if(OrderCalcMargin(t,_Symbol,mn,p,m)&&m<=budget)return NormVol(mn);return 0;}return v;}
int CountPos(){int n=0;for(int i=PositionsTotal()-1;i>=0;i--){ulong t=PositionGetTicket(i);if(t&&PositionGetString(POSITION_SYMBOL)==_Symbol&&PositionGetInteger(POSITION_MAGIC)==InpMagic)n++;}return n;} double BasketProfit(){double p=0;for(int i=PositionsTotal()-1;i>=0;i--){ulong t=PositionGetTicket(i);if(t&&PositionGetString(POSITION_SYMBOL)==_Symbol&&PositionGetInteger(POSITION_MAGIC)==InpMagic)p+=PositionGetDouble(POSITION_PROFIT)+PositionGetDouble(POSITION_SWAP);}return p;}
bool NewestMagicPosition(int &dir,double &price,int &count){count=0;dir=0;price=0;datetime best=0;for(int i=PositionsTotal()-1;i>=0;i--){ulong t=PositionGetTicket(i);if(!t||PositionGetString(POSITION_SYMBOL)!=_Symbol||PositionGetInteger(POSITION_MAGIC)!=InpMagic)continue;count++;datetime ot=(datetime)PositionGetInteger(POSITION_TIME);if(ot>=best){best=ot;dir=PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY?1:-1;price=PositionGetDouble(POSITION_PRICE_OPEN);}}return count>0;}
string StateFile(){return StringFormat("ApexState_%I64d.json",InpMagic);}
void SaveState(){int h=FileOpen(StateFile(),FILE_WRITE|FILE_TXT|FILE_ANSI);if(h==INVALID_HANDLE)return;FileWriteString(h,StringFormat("{\"campId\":\"%s\",\"campSig\":\"%s\",\"campDir\":%d,\"layers\":%d,\"cycleStart\":%.2f,\"targetEq\":%.2f,\"campStart\":%I64d,\"lastAdd\":%.5f,\"mfe\":%.2f,\"mae\":%.2f,\"peakProfitPct\":%.2f,\"floorProfitPct\":%.2f}",campId,campSig,campDir,layers,cycleStart,targetEq,(long)campStart,lastAdd,mfe,mae,peakProfitPct,floorProfitPct));FileClose(h);}
void ClearState(){FileDelete(StateFile());}
bool LoadState(string &j){int h=FileOpen(StateFile(),FILE_READ|FILE_TXT|FILE_ANSI);if(h==INVALID_HANDLE)return false;j="";while(!FileIsEnding(h))j+=FileReadString(h);FileClose(h);return StringLen(j)>0;}
bool OpenLayer(int dir,double score,string why){double pct=MathMin(100.0,C.baseMarginPct*MathPow(C.layerMultiplier,layers));double vol=VolumeForMargin(dir,pct);if(vol<=0){Emit("ADD_BLOCKED",",\"reason\":\"NO_MARGIN_CAPACITY\"");return false;}trade.SetExpertMagicNumber(InpMagic);trade.SetDeviationInPoints(80);string com=StringFormat("APEX L%d %.0f",layers+1,score);bool ok=dir>0?trade.Buy(vol,_Symbol,0,0,0,com):trade.Sell(vol,_Symbol,0,0,0,com);if(!ok){Emit("ORDER_FAIL",StringFormat(",\"retcode\":%d",trade.ResultRetcode()));return false;}layers++;lastAdd=dir>0?SymbolInfoDouble(_Symbol,SYMBOL_ASK):SymbolInfoDouble(_Symbol,SYMBOL_BID);SaveState();Emit("LAYER_OPEN",StringFormat(",\"layer\":%d,\"volume\":%.4f,\"marginPct\":%.2f,\"score\":%.2f,\"reason\":\"%s\",\"price\":%.5f",layers,vol,pct,score,why,lastAdd));return true;}
bool CloseAll(){trade.SetExpertMagicNumber(InpMagic);for(int pass=0;pass<6;pass++){bool any=false;for(int i=PositionsTotal()-1;i>=0;i--){ulong t=PositionGetTicket(i);if(t&&PositionGetString(POSITION_SYMBOL)==_Symbol&&PositionGetInteger(POSITION_MAGIC)==InpMagic){any=true;trade.PositionClose(t);}}if(!any)break;Sleep(100);}return CountPos()==0;}
void Start(Snap &s){camp=true;campDir=s.dir;layers=0;cycleStart=AccountInfoDouble(ACCOUNT_BALANCE);targetEq=C.targetMode=="EQUITY"?C.targetEquity:(C.accountProfile=="NORMAL"?cycleStart*(1.0+C.normalTargetProfitPct/100.0):cycleStart*C.targetMultiplier);peakProfitPct=0;floorProfitPct=0;campStart=TimeCurrent();campId=StringFormat("%I64d-%I64d",AccountInfoInteger(ACCOUNT_LOGIN),(long)campStart);campSig=s.sig;mfe=0;mae=0;Emit("CAMPAIGN_START",StringFormat(",\"score\":%.2f,\"targetEquity\":%.2f,\"entryPrice\":%.5f,\"impulseMult\":%.3f,\"wickRatio\":%.3f,\"m3\":%s,\"m5\":%s,\"atr\":%.5f",s.score,targetEq,s.price,s.impulseMult,s.wickRatio,s.m3?"true":"false",s.m5?"true":"false",s.atr));if(!OpenLayer(campDir,s.score,"PROBE_CONFIRMED")){camp=false;campId="";ClearState();}watch=false;}
void Finish(string outcome,string why){Emit("CAMPAIGN_END",StringFormat(",\"outcome\":\"%s\",\"reason\":\"%s\",\"mfe\":%.2f,\"mae\":%.2f,\"durationSec\":%d",outcome,why,mfe,mae,(int)(TimeCurrent()-campStart)));camp=false;campDir=0;layers=0;lastAdd=0;peakProfitPct=0;floorProfitPct=0;lastEnd=TimeCurrent();campId="";campSig="";watch=false;ClearState();}
Snap AddSignal(){Snap s=Observe();if(s.dir!=campDir){s.valid=false;MqlRates m1[];if(!Rates(PERIOD_M1,30,m1))return s;s.atr=ATR();s.dir=campDir;s.price=campDir>0?SymbolInfoDouble(_Symbol,SYMBOL_BID):SymbolInfoDouble(_Symbol,SYMBOL_ASK);bool cont=campDir<0?(m1[1].close<m1[2].low&&m1[2].close<m1[3].low):(m1[1].close>m1[2].high&&m1[2].close>m1[3].high);bool pf=campDir<0?(m1[2].close>m1[2].open&&m1[1].close<m1[2].low):(m1[2].close<m1[2].open&&m1[1].close>m1[2].high);s.continuation=cont;s.pullbackFail=pf;s.score=60+(cont?20:0)+(pf?15:0);s.sig=campSig;s.reason=cont?"CONTINUATION_BREAK":pf?"FAILED_PULLBACK":"NO_NEW_CONFIRMATION";}return s;}
void Manage(){int n=CountPos();if(n==0){if(camp)Finish("POSITIONS_GONE","BROKER_CLOSE_OR_MARGIN_STOP_OUT");return;}double p=BasketProfit(),campEq=cycleStart+p;mfe=MathMax(mfe,p);mae=MathMin(mae,p);double profitPct=cycleStart>0?(p/cycleStart)*100.0:0;peakProfitPct=MathMax(peakProfitPct,profitPct);
if(C.accountProfile=="NORMAL"&&C.normalProfitFloorEnabled&&peakProfitPct>=200.0){double newFloor=(MathFloor(peakProfitPct/100.0)-1.0)*100.0;if(newFloor>floorProfitPct){floorProfitPct=newFloor;SaveState();Emit("PROFIT_FLOOR_RAISED",StringFormat(",\"peakProfitPct\":%.2f,\"floorProfitPct\":%.2f",peakProfitPct,floorProfitPct));}}
if(targetEq>0&&campEq>=targetEq){if(CloseAll())Finish("TARGET_HIT","BASKET_EQUITY_TARGET");return;}
if(C.accountProfile=="NORMAL"&&C.normalProfitFloorEnabled&&floorProfitPct>=100.0&&profitPct<=floorProfitPct){if(CloseAll())Finish("PROFIT_FLOOR_HIT",StringFormat("LOCKED_%.0f_PCT_AFTER_PEAK_%.0f_PCT",floorProfitPct,peakProfitPct));return;}
SaveState();if(!C.armed)return;if(C.maxLayers>0&&layers>=C.maxLayers)return;if(p<=0)return;Snap s=AddSignal();double threshold=C.addScore+(C.learningEnabled?C.learnAddAdj:0);double cur=campDir>0?SymbolInfoDouble(_Symbol,SYMBOL_BID):SymbolInfoDouble(_Symbol,SYMBOL_ASK);bool spaced=lastAdd>0&&(campDir>0?cur>=lastAdd+s.atr*C.addSpacingAtr:cur<=lastAdd-s.atr*C.addSpacingAtr);bool earned=(s.continuation||s.pullbackFail||s.microBreak)&&s.score>=threshold;if(spaced&&earned)OpenLayer(campDir,s.score,s.reason);}
int OnInit(){Defaults();if((bool)MQLInfoInteger(MQL_TESTER))C.armed=true;if(StringFind(_Symbol,"XAU")<0)return INIT_FAILED;hAtr=iATR(_Symbol,PERIOD_M1,14);if(hAtr==INVALID_HANDLE)return INIT_FAILED;EventSetMillisecondTimer(MathMax(100,InpScanMilliseconds));ConfigPoll();Print("APEX_READY ",APEX_VERSION," noSL=true baseMarginPct=",C.baseMarginPct," layerMultiplier=",C.layerMultiplier," tester=",(bool)MQLInfoInteger(MQL_TESTER));return INIT_SUCCEEDED;}void OnDeinit(const int r){EventKillTimer();if(hAtr!=INVALID_HANDLE)IndicatorRelease(hAtr);}void OnTick(){}void OnTimer(){datetime now=TimeCurrent();if(now-lastCfg>=InpConfigPollSeconds){ConfigPoll();lastCfg=now;}if(camp||CountPos()>0){if(!camp&&CountPos()>0){int nDir,nCount;double nPrice;NewestMagicPosition(nDir,nPrice,nCount);string j;if(nCount>0&&LoadState(j)&&ji(j,"campDir",0)==nDir&&StringLen(js(j,"campId",""))>0){camp=true;campId=js(j,"campId","");campSig=js(j,"campSig","RECOVERED");campDir=nDir;layers=(int)MathMax(nCount,ji(j,"layers",nCount));cycleStart=jd(j,"cycleStart",AccountInfoDouble(ACCOUNT_BALANCE));targetEq=jd(j,"targetEq",C.targetMode=="EQUITY"?C.targetEquity:(C.accountProfile=="NORMAL"?cycleStart*(1.0+C.normalTargetProfitPct/100.0):cycleStart*C.targetMultiplier));peakProfitPct=jd(j,"peakProfitPct",0);floorProfitPct=jd(j,"floorProfitPct",0);campStart=(datetime)ji(j,"campStart",(int)now);lastAdd=nPrice;mfe=jd(j,"mfe",0);mae=jd(j,"mae",0);Emit("CAMPAIGN_RECOVERED",StringFormat(",\"source\":\"STATE_FILE\",\"layers\":%d",layers));}else if(nCount>0){camp=true;campDir=nDir;layers=nCount;cycleStart=AccountInfoDouble(ACCOUNT_BALANCE);targetEq=C.targetMode=="EQUITY"?C.targetEquity:(C.accountProfile=="NORMAL"?cycleStart*(1.0+C.normalTargetProfitPct/100.0):cycleStart*C.targetMultiplier);peakProfitPct=0;floorProfitPct=0;campStart=now;campId=StringFormat("RECOVER-%I64d",(long)now);campSig="RECOVERED_NO_STATE";lastAdd=nPrice;mfe=0;mae=0;Emit("CAMPAIGN_RECOVERED",",\"source\":\"POSITION_SCAN_ONLY\",\"warning\":\"CYCLE_START_EQUITY_ESTIMATED_FROM_RESTART_BALANCE\"");}SaveState();}Manage();return;}if(!C.armed)return;if(lastEnd>0&&now-lastEnd<C.cooldownMinutes*60)return;Snap s=Observe();if(s.valid)Start(s);}
